package org.ski.dvx.client.hibernate.user_profile;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "UserProfileDAODelegate", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/")
public interface UserProfileDAODelegate {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "save", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.SaveResponse")
	public void save(
			@WebParam(name = "arg0", targetNamespace = "") UserProfile arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "delete", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.Delete")
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.DeleteResponse")
	public void delete(
			@WebParam(name = "arg0", targetNamespace = "") UserProfile arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.user_profile.UserProfile
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "merge", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.Merge")
	@ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.MergeResponse")
	public UserProfile merge(
			@WebParam(name = "arg0", targetNamespace = "") UserProfile arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.user_profile.UserProfile
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findById", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.FindById")
	@ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.FindByIdResponse")
	public UserProfile findById(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByExample", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.FindByExample")
	@ResponseWrapper(localName = "findByExampleResponse", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.FindByExampleResponse")
	public List<Object> findByExample(
			@WebParam(name = "arg0", targetNamespace = "") UserProfile arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByProperty", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.FindByProperty")
	@ResponseWrapper(localName = "findByPropertyResponse", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.FindByPropertyResponse")
	public List<Object> findByProperty(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") Object arg1);

	/**
	 * 
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAll", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.FindAll")
	@ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.FindAllResponse")
	public List<Object> findAll();

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachDirty", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.AttachDirty")
	@ResponseWrapper(localName = "attachDirtyResponse", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.AttachDirtyResponse")
	public void attachDirty(
			@WebParam(name = "arg0", targetNamespace = "") UserProfile arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachClean", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.AttachClean")
	@ResponseWrapper(localName = "attachCleanResponse", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.AttachCleanResponse")
	public void attachClean(
			@WebParam(name = "arg0", targetNamespace = "") UserProfile arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByModified", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.FindByModified")
	@ResponseWrapper(localName = "findByModifiedResponse", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.FindByModifiedResponse")
	public List<Object> findByModified(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCreated", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.FindByCreated")
	@ResponseWrapper(localName = "findByCreatedResponse", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.FindByCreatedResponse")
	public List<Object> findByCreated(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserFk", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.FindByUserFk")
	@ResponseWrapper(localName = "findByUserFkResponse", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.FindByUserFkResponse")
	public List<Object> findByUserFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserDetailFk", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.FindByUserDetailFk")
	@ResponseWrapper(localName = "findByUserDetailFkResponse", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.FindByUserDetailFkResponse")
	public List<Object> findByUserDetailFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserProfileVisionImpared", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.FindByUserProfileVisionImpared")
	@ResponseWrapper(localName = "findByUserProfileVisionImparedResponse", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.FindByUserProfileVisionImparedResponse")
	public List<Object> findByUserProfileVisionImpared(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserProfileMotionImpared", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.FindByUserProfileMotionImpared")
	@ResponseWrapper(localName = "findByUserProfileMotionImparedResponse", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_profile.FindByUserProfileMotionImparedResponse")
	public List<Object> findByUserProfileMotionImpared(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

}
