package org.ski.dvx.client.hibernate.user_profile;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * UserProfileDAOService service = new UserProfileDAOService();
 * UserProfileDAODelegate portType = service.getUserProfileDAOPort();
 * portType.save(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "UserProfileDAOService", targetNamespace = "http://user_profile.hibernate.server.dvx.ski.org/", wsdlLocation = "http://localhost:8080/dvx/UserProfileDAOPort?wsdl")
public class UserProfileDAOService extends Service {

	private final static URL USERPROFILEDAOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.ski.dvx.client.hibernate.user_profile.UserProfileDAOService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.ski.dvx.client.hibernate.user_profile.UserProfileDAOService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/dvx/UserProfileDAOPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/dvx/UserProfileDAOPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		USERPROFILEDAOSERVICE_WSDL_LOCATION = url;
	}

	public UserProfileDAOService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public UserProfileDAOService() {
		super(USERPROFILEDAOSERVICE_WSDL_LOCATION, new QName(
				"http://user_profile.hibernate.server.dvx.ski.org/",
				"UserProfileDAOService"));
	}

	/**
	 * 
	 * @return returns UserProfileDAODelegate
	 */
	@WebEndpoint(name = "UserProfileDAOPort")
	public UserProfileDAODelegate getUserProfileDAOPort() {
		return super.getPort(new QName(
				"http://user_profile.hibernate.server.dvx.ski.org/",
				"UserProfileDAOPort"), UserProfileDAODelegate.class);
	}

}
