package org.ski.dvx.client.hibernate.crew_cast;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * CrewCastDAOService service = new CrewCastDAOService();
 * CrewCastDAODelegate portType = service.getCrewCastDAOPort();
 * portType.save(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "CrewCastDAOService", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", wsdlLocation = "http://localhost:8080/dvx/CrewCastDAOPort?wsdl")
public class CrewCastDAOService extends Service {

	private final static URL CREWCASTDAOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.ski.dvx.client.hibernate.crew_cast.CrewCastDAOService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.ski.dvx.client.hibernate.crew_cast.CrewCastDAOService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/dvx/CrewCastDAOPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/dvx/CrewCastDAOPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CREWCASTDAOSERVICE_WSDL_LOCATION = url;
	}

	public CrewCastDAOService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CrewCastDAOService() {
		super(CREWCASTDAOSERVICE_WSDL_LOCATION, new QName(
				"http://crew_cast.hibernate.server.dvx.ski.org/",
				"CrewCastDAOService"));
	}

	/**
	 * 
	 * @return returns CrewCastDAODelegate
	 */
	@WebEndpoint(name = "CrewCastDAOPort")
	public CrewCastDAODelegate getCrewCastDAOPort() {
		return super.getPort(new QName(
				"http://crew_cast.hibernate.server.dvx.ski.org/",
				"CrewCastDAOPort"), CrewCastDAODelegate.class);
	}

}
