package org.ski.dvx.client.hibernate.audio_track_info;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * AudioTrackInfoDAOService service = new AudioTrackInfoDAOService();
 * AudioTrackInfoDAODelegate portType = service.getAudioTrackInfoDAOPort();
 * portType.save(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "AudioTrackInfoDAOService", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", wsdlLocation = "http://localhost:8080/dvx/AudioTrackInfoDAOPort?wsdl")
public class AudioTrackInfoDAOService extends Service {

	private final static URL AUDIOTRACKINFODAOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.ski.dvx.client.hibernate.audio_track_info.AudioTrackInfoDAOService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.ski.dvx.client.hibernate.audio_track_info.AudioTrackInfoDAOService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/dvx/AudioTrackInfoDAOPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/dvx/AudioTrackInfoDAOPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		AUDIOTRACKINFODAOSERVICE_WSDL_LOCATION = url;
	}

	public AudioTrackInfoDAOService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public AudioTrackInfoDAOService() {
		super(AUDIOTRACKINFODAOSERVICE_WSDL_LOCATION, new QName(
				"http://audio_track_info.hibernate.server.dvx.ski.org/",
				"AudioTrackInfoDAOService"));
	}

	/**
	 * 
	 * @return returns AudioTrackInfoDAODelegate
	 */
	@WebEndpoint(name = "AudioTrackInfoDAOPort")
	public AudioTrackInfoDAODelegate getAudioTrackInfoDAOPort() {
		return super.getPort(new QName(
				"http://audio_track_info.hibernate.server.dvx.ski.org/",
				"AudioTrackInfoDAOPort"), AudioTrackInfoDAODelegate.class);
	}

}
