package org.ski.dvx.client.hibernate.audio_track_info;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "AudioTrackInfoDAODelegate", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/")
public interface AudioTrackInfoDAODelegate {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "save", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.SaveResponse")
	public void save(
			@WebParam(name = "arg0", targetNamespace = "") AudioTrackInfo arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "delete", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.Delete")
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.DeleteResponse")
	public void delete(
			@WebParam(name = "arg0", targetNamespace = "") AudioTrackInfo arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns
	 *         org.ski.dvx.client.hibernate.audio_track_info.AudioTrackInfo
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "merge", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.Merge")
	@ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.MergeResponse")
	public AudioTrackInfo merge(
			@WebParam(name = "arg0", targetNamespace = "") AudioTrackInfo arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns
	 *         org.ski.dvx.client.hibernate.audio_track_info.AudioTrackInfo
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findById", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.FindById")
	@ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.FindByIdResponse")
	public AudioTrackInfo findById(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByExample", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.FindByExample")
	@ResponseWrapper(localName = "findByExampleResponse", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.FindByExampleResponse")
	public List<Object> findByExample(
			@WebParam(name = "arg0", targetNamespace = "") AudioTrackInfo arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByProperty", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.FindByProperty")
	@ResponseWrapper(localName = "findByPropertyResponse", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.FindByPropertyResponse")
	public List<Object> findByProperty(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") Object arg1);

	/**
	 * 
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAll", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.FindAll")
	@ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.FindAllResponse")
	public List<Object> findAll();

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachDirty", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.AttachDirty")
	@ResponseWrapper(localName = "attachDirtyResponse", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.AttachDirtyResponse")
	public void attachDirty(
			@WebParam(name = "arg0", targetNamespace = "") AudioTrackInfo arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachClean", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.AttachClean")
	@ResponseWrapper(localName = "attachCleanResponse", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.AttachCleanResponse")
	public void attachClean(
			@WebParam(name = "arg0", targetNamespace = "") AudioTrackInfo arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByModified", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.FindByModified")
	@ResponseWrapper(localName = "findByModifiedResponse", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.FindByModifiedResponse")
	public List<Object> findByModified(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCreated", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.FindByCreated")
	@ResponseWrapper(localName = "findByCreatedResponse", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.FindByCreatedResponse")
	public List<Object> findByCreated(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByAudioTrackDescription", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.FindByAudioTrackDescription")
	@ResponseWrapper(localName = "findByAudioTrackDescriptionResponse", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.FindByAudioTrackDescriptionResponse")
	public List<Object> findByAudioTrackDescription(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByAudioTrackGain", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.FindByAudioTrackGain")
	@ResponseWrapper(localName = "findByAudioTrackGainResponse", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.FindByAudioTrackGainResponse")
	public List<Object> findByAudioTrackGain(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByAudioTrackPan", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.FindByAudioTrackPan")
	@ResponseWrapper(localName = "findByAudioTrackPanResponse", targetNamespace = "http://audio_track_info.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.audio_track_info.FindByAudioTrackPanResponse")
	public List<Object> findByAudioTrackPan(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

}
