package org.ski.dvx.client.hibernate.country;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * CountryDAOService service = new CountryDAOService();
 * CountryDAODelegate portType = service.getCountryDAOPort();
 * portType.save(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "CountryDAOService", targetNamespace = "http://country.hibernate.server.dvx.ski.org/", wsdlLocation = "http://localhost:8080/dvx/CountryDAOPort?wsdl")
public class CountryDAOService extends Service {

	private final static URL COUNTRYDAOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.ski.dvx.client.hibernate.country.CountryDAOService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.ski.dvx.client.hibernate.country.CountryDAOService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/dvx/CountryDAOPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/dvx/CountryDAOPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		COUNTRYDAOSERVICE_WSDL_LOCATION = url;
	}

	public CountryDAOService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CountryDAOService() {
		super(COUNTRYDAOSERVICE_WSDL_LOCATION, new QName(
				"http://country.hibernate.server.dvx.ski.org/",
				"CountryDAOService"));
	}

	/**
	 * 
	 * @return returns CountryDAODelegate
	 */
	@WebEndpoint(name = "CountryDAOPort")
	public CountryDAODelegate getCountryDAOPort() {
		return super.getPort(new QName(
				"http://country.hibernate.server.dvx.ski.org/",
				"CountryDAOPort"), CountryDAODelegate.class);
	}

}
