/*
	Project:		DVX_App_Demo	
	File Name:		MovieDescription.java
	Designer:		Josh Miele
	Author:			Greg
	Contributors:	Owen Edwards					
	Created:		Oct 3, 2011	
	Copyright:	 	The Smith-Kettlewell Eye Research Institute
					© 2011 - 2011
					All Rights Reserved
					
					http://www.ski.org/
					
					The Smith-Kettlewell Eye Research Institute
					2318 Fillmore Street 
					San Francisco, CA  94115 
					415-345-2000  
				 
	Notice:			Parts of this project are based on Open Source 
					and/or Public Domain Code. Please use good judgement 
					if you include any of this project in your project.
					
	Contact:		Josh Miele
					jam@ski.org
*/

/** Class starts here **/
package org.ski.dvx.app.dialogs;

/**
 * @author Greg
 *
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MovieDescription.java
 *
 * Created on Oct 3, 2011, 7:57:10 PM
 */

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;

import org.ski.dvx.app.DVX_Constants;
import org.ski.dvx.app.DVX_PlaySound;
import org.ski.dvx.app.DVX_Player;
import org.ski.dvx.app.DVX_RecordButton;
import org.ski.dvx.hibernate.Description;
import org.ski.dvx.hibernate.Movie;

/**
 *
 * @author Greg
 */
public class MovieDescription extends javax.swing.JFrame {
	
	DVX_Player dvx_player;	

    /** Creates new form MovieDescription */
    public MovieDescription(DVX_Player dvx_player) {
        this.dvx_player = dvx_player;
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        // Determine the new location of the window
        int w = getSize().width;
        int h = getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;

        // Move the window
        setLocation(x, y);   
        
        jTextFieldMovieDescription.setText(dvx_player.getMovie().getMovieDescription());
        jTextFieldMovieID.setText("" + dvx_player.getMovie().getMovieId());
        jTextFieldMovieName.setText(dvx_player.getMovie().getMovieName());
        jTextFieldMovieSBNNumber.setText(dvx_player.getMovie().getMovieSbnNumber());
    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabelDVXMovieDescription = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonCancel = new javax.swing.JButton();
        jButtonSaveDescription = new javax.swing.JButton();
        jButtonRecordDescription = new DVX_RecordButton(dvx_player, "Record Description");
        jLabelMovieID = new javax.swing.JLabel();
        jLabelMovieName = new javax.swing.JLabel();
        jLabelMovieDescription = new javax.swing.JLabel();
        jLabelMovieSBNNumber = new javax.swing.JLabel();
        jTextFieldMovieID = new javax.swing.JTextField();
        jTextFieldMovieName = new javax.swing.JTextField();
        jTextFieldMovieSBNNumber = new javax.swing.JTextField();
        jTextFieldMovieDescription = new javax.swing.JTextArea();
        jButtonPlayDescription = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelDVXMovieDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDVXMovieDescription.setText("DVX Movie Description");

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonSaveDescription.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonSaveDescription.setText("Save Description");
        jButtonSaveDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveDescriptionActionPerformed(evt);
            }
        });

        jButtonRecordDescription.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRecordDescription.setText("Record Description");
/*        jButtonRecordDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecordDescriptionActionPerformed(evt);
            }
        }); */

        jLabelMovieID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMovieID.setText("Movie ID:");

        jLabelMovieName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMovieName.setText("Movie Name:");

        jLabelMovieDescription.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMovieDescription.setText("Movie Description:");

        jLabelMovieSBNNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMovieSBNNumber.setText("Movie SBN Number:");

        jTextFieldMovieID.setEditable(false);
        jTextFieldMovieID.setText("12345678");
        jTextFieldMovieID.setEnabled(false);

        jTextFieldMovieSBNNumber.setEditable(false);
        jTextFieldMovieSBNNumber.setText("abc123");
        jTextFieldMovieSBNNumber.setEnabled(false);

//        jTextFieldMovieDescription.setHorizontalAlignment(javax.swing.JTextField.LEFT);
//        jTextFieldMovieDescription.setToolTipText("");

        jButtonPlayDescription.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonPlayDescription.setText("Play Description");
        jButtonPlayDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayDescriptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDVXMovieDescription)
                .addContainerGap(365, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPlayDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButtonRecordDescription)
                .addGap(18, 18, 18)
                .addComponent(jButtonSaveDescription)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancel)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelMovieID)
                                .addComponent(jLabelMovieSBNNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelMovieName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMovieID, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                            .addComponent(jTextFieldMovieSBNNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                            .addComponent(jTextFieldMovieName, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMovieDescription)
                            .addComponent(jTextFieldMovieDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDVXMovieDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMovieID)
                    .addComponent(jTextFieldMovieID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMovieName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMovieName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMovieSBNNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMovieSBNNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMovieDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldMovieDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonSaveDescription)
                    .addComponent(jButtonRecordDescription)
                    .addComponent(jButtonPlayDescription))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

private void jButtonPlayDescriptionActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
	
	if(new File(DVX_Constants.MOVIE_PATH + // is there a .wav file with the name
			jTextFieldMovieSBNNumber.getText() + 
			DVX_Constants.MOVIE_MENUS_PATH +
			DVX_Constants.MOVIE_NAME_WAV).exists())	// recorded version...
	{
		DVX_PlaySound.playWav(	DVX_Constants.MOVIE_PATH + 
				jTextFieldMovieSBNNumber.getText() + 
							DVX_Constants.MOVIE_MENUS_PATH +
							DVX_Constants.MOVIE_NAME_WAV, true); 
	}
	else
	{
		dvx_player.getDvxSpeak().speak("No movie description audio file found.");
	}
}

private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
    dispose();

}

private void jButtonSaveDescriptionActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
	Movie movie = dvx_player.getMovie();
	movie.setMovieDescription(jTextFieldMovieDescription.getText());
	movie.setMovieName(jTextFieldMovieName.getText());
	dvx_player.getDvxDBSupport().updateMovie(dvx_player.getMovie());
    dispose();
}

//private void jButtonRecordDescriptionActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
//}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieDescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieDescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieDescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieDescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MovieDescription(null ).setVisible(true);
            }
        });
    }
        
    // Variables declaration - do not modify
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonPlayDescription;
    DVX_RecordButton jButtonRecordDescription;
    private javax.swing.JButton jButtonSaveDescription;
    private javax.swing.JLabel jLabelDVXMovieDescription;
    private javax.swing.JLabel jLabelMovieDescription;
    private javax.swing.JLabel jLabelMovieID;
    private javax.swing.JLabel jLabelMovieName;
    private javax.swing.JLabel jLabelMovieSBNNumber;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextFieldMovieDescription;
    private javax.swing.JTextField jTextFieldMovieID;
    private javax.swing.JTextField jTextFieldMovieName;
    private javax.swing.JTextField jTextFieldMovieSBNNumber;
    // End of variables declaration
}
