package org.ski.dvx.client.hibernate.version;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "VersionDAODelegate", targetNamespace = "http://version.hibernate.server.dvx.ski.org/")
public interface VersionDAODelegate {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "save", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.SaveResponse")
	public void save(@WebParam(name = "arg0", targetNamespace = "") Version arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "delete", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.Delete")
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.DeleteResponse")
	public void delete(
			@WebParam(name = "arg0", targetNamespace = "") Version arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.version.Version
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "merge", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.Merge")
	@ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.MergeResponse")
	public Version merge(
			@WebParam(name = "arg0", targetNamespace = "") Version arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.version.Version
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findById", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.FindById")
	@ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.FindByIdResponse")
	public Version findById(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByExample", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.FindByExample")
	@ResponseWrapper(localName = "findByExampleResponse", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.FindByExampleResponse")
	public List<Object> findByExample(
			@WebParam(name = "arg0", targetNamespace = "") Version arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByProperty", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.FindByProperty")
	@ResponseWrapper(localName = "findByPropertyResponse", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.FindByPropertyResponse")
	public List<Object> findByProperty(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") Object arg1);

	/**
	 * 
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAll", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.FindAll")
	@ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.FindAllResponse")
	public List<Object> findAll();

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachDirty", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.AttachDirty")
	@ResponseWrapper(localName = "attachDirtyResponse", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.AttachDirtyResponse")
	public void attachDirty(
			@WebParam(name = "arg0", targetNamespace = "") Version arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachClean", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.AttachClean")
	@ResponseWrapper(localName = "attachCleanResponse", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.AttachCleanResponse")
	public void attachClean(
			@WebParam(name = "arg0", targetNamespace = "") Version arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByModified", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.FindByModified")
	@ResponseWrapper(localName = "findByModifiedResponse", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.FindByModifiedResponse")
	public List<Object> findByModified(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCreated", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.FindByCreated")
	@ResponseWrapper(localName = "findByCreatedResponse", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.FindByCreatedResponse")
	public List<Object> findByCreated(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByAuthorFk", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.FindByAuthorFk")
	@ResponseWrapper(localName = "findByAuthorFkResponse", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.FindByAuthorFkResponse")
	public List<Object> findByAuthorFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieFk", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.FindByMovieFk")
	@ResponseWrapper(localName = "findByMovieFkResponse", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.FindByMovieFkResponse")
	public List<Object> findByMovieFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByVersionDescription", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.FindByVersionDescription")
	@ResponseWrapper(localName = "findByVersionDescriptionResponse", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.FindByVersionDescriptionResponse")
	public List<Object> findByVersionDescription(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByLanguageFk", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.FindByLanguageFk")
	@ResponseWrapper(localName = "findByLanguageFkResponse", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.version.FindByLanguageFkResponse")
	public List<Object> findByLanguageFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

}
