package org.ski.dvx.client.hibernate.version;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * VersionDAOService service = new VersionDAOService();
 * VersionDAODelegate portType = service.getVersionDAOPort();
 * portType.save(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "VersionDAOService", targetNamespace = "http://version.hibernate.server.dvx.ski.org/", wsdlLocation = "http://localhost:8080/dvx/VersionDAOPort?wsdl")
public class VersionDAOService extends Service {

	private final static URL VERSIONDAOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.ski.dvx.client.hibernate.version.VersionDAOService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.ski.dvx.client.hibernate.version.VersionDAOService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/dvx/VersionDAOPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/dvx/VersionDAOPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		VERSIONDAOSERVICE_WSDL_LOCATION = url;
	}

	public VersionDAOService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public VersionDAOService() {
		super(VERSIONDAOSERVICE_WSDL_LOCATION, new QName(
				"http://version.hibernate.server.dvx.ski.org/",
				"VersionDAOService"));
	}

	/**
	 * 
	 * @return returns VersionDAODelegate
	 */
	@WebEndpoint(name = "VersionDAOPort")
	public VersionDAODelegate getVersionDAOPort() {
		return super.getPort(new QName(
				"http://version.hibernate.server.dvx.ski.org/",
				"VersionDAOPort"), VersionDAODelegate.class);
	}

}
