package org.ski.dvx.client.hibernate.description;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "DescriptionDAODelegate", targetNamespace = "http://description.hibernate.server.dvx.ski.org/")
public interface DescriptionDAODelegate {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "save", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.SaveResponse")
	public void save(
			@WebParam(name = "arg0", targetNamespace = "") Description arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "delete", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.Delete")
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.DeleteResponse")
	public void delete(
			@WebParam(name = "arg0", targetNamespace = "") Description arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.description.Description
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "merge", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.Merge")
	@ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.MergeResponse")
	public Description merge(
			@WebParam(name = "arg0", targetNamespace = "") Description arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.description.Description
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findById", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindById")
	@ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByIdResponse")
	public Description findById(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByExample", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByExample")
	@ResponseWrapper(localName = "findByExampleResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByExampleResponse")
	public List<Object> findByExample(
			@WebParam(name = "arg0", targetNamespace = "") Description arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByProperty", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByProperty")
	@ResponseWrapper(localName = "findByPropertyResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByPropertyResponse")
	public List<Object> findByProperty(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") Object arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescriptionLanguageFk", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionLanguageFk")
	@ResponseWrapper(localName = "findByDescriptionLanguageFkResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionLanguageFkResponse")
	public List<Object> findByDescriptionLanguageFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAll", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindAll")
	@ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindAllResponse")
	public List<Object> findAll();

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachDirty", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.AttachDirty")
	@ResponseWrapper(localName = "attachDirtyResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.AttachDirtyResponse")
	public void attachDirty(
			@WebParam(name = "arg0", targetNamespace = "") Description arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachClean", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.AttachClean")
	@ResponseWrapper(localName = "attachCleanResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.AttachCleanResponse")
	public void attachClean(
			@WebParam(name = "arg0", targetNamespace = "") Description arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByModified", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByModified")
	@ResponseWrapper(localName = "findByModifiedResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByModifiedResponse")
	public List<Object> findByModified(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCreated", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByCreated")
	@ResponseWrapper(localName = "findByCreatedResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByCreatedResponse")
	public List<Object> findByCreated(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByAuthorFk", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByAuthorFk")
	@ResponseWrapper(localName = "findByAuthorFkResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByAuthorFkResponse")
	public List<Object> findByAuthorFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieFk", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByMovieFk")
	@ResponseWrapper(localName = "findByMovieFkResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByMovieFkResponse")
	public List<Object> findByMovieFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescriptionTitleId", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionTitleId")
	@ResponseWrapper(localName = "findByDescriptionTitleIdResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionTitleIdResponse")
	public List<Object> findByDescriptionTitleId(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescriptionActive", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionActive")
	@ResponseWrapper(localName = "findByDescriptionActiveResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionActiveResponse")
	public List<Object> findByDescriptionActive(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescriptionChapter", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionChapter")
	@ResponseWrapper(localName = "findByDescriptionChapterResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionChapterResponse")
	public List<Object> findByDescriptionChapter(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescriptionStartTimeInt", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionStartTimeInt")
	@ResponseWrapper(localName = "findByDescriptionStartTimeIntResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionStartTimeIntResponse")
	public List<Object> findByDescriptionStartTimeInt(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescriptionStartFrame", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionStartFrame")
	@ResponseWrapper(localName = "findByDescriptionStartFrameResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionStartFrameResponse")
	public List<Object> findByDescriptionStartFrame(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescriptionOrder", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionOrder")
	@ResponseWrapper(localName = "findByDescriptionOrderResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionOrderResponse")
	public List<Object> findByDescriptionOrder(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescriptionTypeEnum", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionTypeEnum")
	@ResponseWrapper(localName = "findByDescriptionTypeEnumResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionTypeEnumResponse")
	public List<Object> findByDescriptionTypeEnum(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescriptionLong", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionLong")
	@ResponseWrapper(localName = "findByDescriptionLongResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionLongResponse")
	public List<Object> findByDescriptionLong(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescriptionShort", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionShort")
	@ResponseWrapper(localName = "findByDescriptionShortResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionShortResponse")
	public List<Object> findByDescriptionShort(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescriptionMetaData", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionMetaData")
	@ResponseWrapper(localName = "findByDescriptionMetaDataResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionMetaDataResponse")
	public List<Object> findByDescriptionMetaData(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescriptionMetaXml", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionMetaXml")
	@ResponseWrapper(localName = "findByDescriptionMetaXmlResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionMetaXmlResponse")
	public List<Object> findByDescriptionMetaXml(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescriptionVersion", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionVersion")
	@ResponseWrapper(localName = "findByDescriptionVersionResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionVersionResponse")
	public List<Object> findByDescriptionVersion(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescriptionPathFk", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionPathFk")
	@ResponseWrapper(localName = "findByDescriptionPathFkResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionPathFkResponse")
	public List<Object> findByDescriptionPathFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescriptionUri", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionUri")
	@ResponseWrapper(localName = "findByDescriptionUriResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionUriResponse")
	public List<Object> findByDescriptionUri(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescriptionTimeOffset", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionTimeOffset")
	@ResponseWrapper(localName = "findByDescriptionTimeOffsetResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionTimeOffsetResponse")
	public List<Object> findByDescriptionTimeOffset(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescriptionStartTimeText", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionStartTimeText")
	@ResponseWrapper(localName = "findByDescriptionStartTimeTextResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionStartTimeTextResponse")
	public List<Object> findByDescriptionStartTimeText(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescriptionEndTimeInt", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionEndTimeInt")
	@ResponseWrapper(localName = "findByDescriptionEndTimeIntResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionEndTimeIntResponse")
	public List<Object> findByDescriptionEndTimeInt(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescriptionEndTimeText", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionEndTimeText")
	@ResponseWrapper(localName = "findByDescriptionEndTimeTextResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionEndTimeTextResponse")
	public List<Object> findByDescriptionEndTimeText(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescriptionDurationInt", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionDurationInt")
	@ResponseWrapper(localName = "findByDescriptionDurationIntResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionDurationIntResponse")
	public List<Object> findByDescriptionDurationInt(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescriptionDurationText", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionDurationText")
	@ResponseWrapper(localName = "findByDescriptionDurationTextResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionDurationTextResponse")
	public List<Object> findByDescriptionDurationText(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescriptionRatingTotal", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionRatingTotal")
	@ResponseWrapper(localName = "findByDescriptionRatingTotalResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionRatingTotalResponse")
	public List<Object> findByDescriptionRatingTotal(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescriptionCompression", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionCompression")
	@ResponseWrapper(localName = "findByDescriptionCompressionResponse", targetNamespace = "http://description.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.description.FindByDescriptionCompressionResponse")
	public List<Object> findByDescriptionCompression(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

}
