package org.ski.dvx.client.hibernate.crew_cast;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CrewCastDAODelegate", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/")
public interface CrewCastDAODelegate {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "save", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.SaveResponse")
	public void save(
			@WebParam(name = "arg0", targetNamespace = "") CrewCast arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "delete", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.Delete")
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.DeleteResponse")
	public void delete(
			@WebParam(name = "arg0", targetNamespace = "") CrewCast arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.crew_cast.CrewCast
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "merge", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.Merge")
	@ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.MergeResponse")
	public CrewCast merge(
			@WebParam(name = "arg0", targetNamespace = "") CrewCast arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.crew_cast.CrewCast
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findById", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindById")
	@ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByIdResponse")
	public CrewCast findById(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByExample", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByExample")
	@ResponseWrapper(localName = "findByExampleResponse", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByExampleResponse")
	public List<Object> findByExample(
			@WebParam(name = "arg0", targetNamespace = "") CrewCast arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByProperty", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByProperty")
	@ResponseWrapper(localName = "findByPropertyResponse", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByPropertyResponse")
	public List<Object> findByProperty(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") Object arg1);

	/**
	 * 
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAll", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindAll")
	@ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindAllResponse")
	public List<Object> findAll();

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachDirty", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.AttachDirty")
	@ResponseWrapper(localName = "attachDirtyResponse", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.AttachDirtyResponse")
	public void attachDirty(
			@WebParam(name = "arg0", targetNamespace = "") CrewCast arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachClean", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.AttachClean")
	@ResponseWrapper(localName = "attachCleanResponse", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.AttachCleanResponse")
	public void attachClean(
			@WebParam(name = "arg0", targetNamespace = "") CrewCast arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByModified", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByModified")
	@ResponseWrapper(localName = "findByModifiedResponse", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByModifiedResponse")
	public List<Object> findByModified(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCreated", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByCreated")
	@ResponseWrapper(localName = "findByCreatedResponse", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByCreatedResponse")
	public List<Object> findByCreated(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCrewCastFullName", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByCrewCastFullName")
	@ResponseWrapper(localName = "findByCrewCastFullNameResponse", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByCrewCastFullNameResponse")
	public List<Object> findByCrewCastFullName(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCrewCastFirstName", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByCrewCastFirstName")
	@ResponseWrapper(localName = "findByCrewCastFirstNameResponse", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByCrewCastFirstNameResponse")
	public List<Object> findByCrewCastFirstName(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCrewCastMiddleName", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByCrewCastMiddleName")
	@ResponseWrapper(localName = "findByCrewCastMiddleNameResponse", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByCrewCastMiddleNameResponse")
	public List<Object> findByCrewCastMiddleName(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCrewCastLastName", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByCrewCastLastName")
	@ResponseWrapper(localName = "findByCrewCastLastNameResponse", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByCrewCastLastNameResponse")
	public List<Object> findByCrewCastLastName(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCrewCastBirthday", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByCrewCastBirthday")
	@ResponseWrapper(localName = "findByCrewCastBirthdayResponse", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByCrewCastBirthdayResponse")
	public List<Object> findByCrewCastBirthday(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCrewCastDescription", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByCrewCastDescription")
	@ResponseWrapper(localName = "findByCrewCastDescriptionResponse", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByCrewCastDescriptionResponse")
	public List<Object> findByCrewCastDescription(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCrewCastBiography", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByCrewCastBiography")
	@ResponseWrapper(localName = "findByCrewCastBiographyResponse", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByCrewCastBiographyResponse")
	public List<Object> findByCrewCastBiography(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCrewCastAuthorFk", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByCrewCastAuthorFk")
	@ResponseWrapper(localName = "findByCrewCastAuthorFkResponse", targetNamespace = "http://crew_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.crew_cast.FindByCrewCastAuthorFkResponse")
	public List<Object> findByCrewCastAuthorFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

}
