package org.ski.dvx.client.hibernate.city;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CityDAODelegate", targetNamespace = "http://city.hibernate.server.dvx.ski.org/")
public interface CityDAODelegate {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "save", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.SaveResponse")
	public void save(@WebParam(name = "arg0", targetNamespace = "") City arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "delete", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.Delete")
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.DeleteResponse")
	public void delete(@WebParam(name = "arg0", targetNamespace = "") City arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.city.City
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "merge", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.Merge")
	@ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.MergeResponse")
	public City merge(@WebParam(name = "arg0", targetNamespace = "") City arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.city.City
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findById", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.FindById")
	@ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.FindByIdResponse")
	public City findById(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByExample", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.FindByExample")
	@ResponseWrapper(localName = "findByExampleResponse", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.FindByExampleResponse")
	public List<Object> findByExample(
			@WebParam(name = "arg0", targetNamespace = "") City arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByProperty", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.FindByProperty")
	@ResponseWrapper(localName = "findByPropertyResponse", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.FindByPropertyResponse")
	public List<Object> findByProperty(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") Object arg1);

	/**
	 * 
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAll", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.FindAll")
	@ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.FindAllResponse")
	public List<Object> findAll();

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachDirty", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.AttachDirty")
	@ResponseWrapper(localName = "attachDirtyResponse", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.AttachDirtyResponse")
	public void attachDirty(
			@WebParam(name = "arg0", targetNamespace = "") City arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachClean", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.AttachClean")
	@ResponseWrapper(localName = "attachCleanResponse", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.AttachCleanResponse")
	public void attachClean(
			@WebParam(name = "arg0", targetNamespace = "") City arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByModified", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.FindByModified")
	@ResponseWrapper(localName = "findByModifiedResponse", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.FindByModifiedResponse")
	public List<Object> findByModified(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCreated", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.FindByCreated")
	@ResponseWrapper(localName = "findByCreatedResponse", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.FindByCreatedResponse")
	public List<Object> findByCreated(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCityName", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.FindByCityName")
	@ResponseWrapper(localName = "findByCityNameResponse", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.FindByCityNameResponse")
	public List<Object> findByCityName(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCityZipCodeFk", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.FindByCityZipCodeFk")
	@ResponseWrapper(localName = "findByCityZipCodeFkResponse", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.FindByCityZipCodeFkResponse")
	public List<Object> findByCityZipCodeFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCityStateFk", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.FindByCityStateFk")
	@ResponseWrapper(localName = "findByCityStateFkResponse", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.FindByCityStateFkResponse")
	public List<Object> findByCityStateFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCityCountryFk", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.FindByCityCountryFk")
	@ResponseWrapper(localName = "findByCityCountryFkResponse", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.FindByCityCountryFkResponse")
	public List<Object> findByCityCountryFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCityGeoCodeFk", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.FindByCityGeoCodeFk")
	@ResponseWrapper(localName = "findByCityGeoCodeFkResponse", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.FindByCityGeoCodeFkResponse")
	public List<Object> findByCityGeoCodeFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCityPopulation", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.FindByCityPopulation")
	@ResponseWrapper(localName = "findByCityPopulationResponse", targetNamespace = "http://city.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.city.FindByCityPopulationResponse")
	public List<Object> findByCityPopulation(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

}
