package org.ski.dvx.client.hibernate.movie_chapter;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MovieChapterDAODelegate", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/")
public interface MovieChapterDAODelegate {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "save", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.SaveResponse")
	public void save(
			@WebParam(name = "arg0", targetNamespace = "") MovieChapter arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "delete", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.Delete")
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.DeleteResponse")
	public void delete(
			@WebParam(name = "arg0", targetNamespace = "") MovieChapter arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.movie_chapter.MovieChapter
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "merge", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.Merge")
	@ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.MergeResponse")
	public MovieChapter merge(
			@WebParam(name = "arg0", targetNamespace = "") MovieChapter arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.movie_chapter.MovieChapter
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findById", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.FindById")
	@ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.FindByIdResponse")
	public MovieChapter findById(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByExample", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.FindByExample")
	@ResponseWrapper(localName = "findByExampleResponse", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.FindByExampleResponse")
	public List<Object> findByExample(
			@WebParam(name = "arg0", targetNamespace = "") MovieChapter arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByProperty", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.FindByProperty")
	@ResponseWrapper(localName = "findByPropertyResponse", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.FindByPropertyResponse")
	public List<Object> findByProperty(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") Object arg1);

	/**
	 * 
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAll", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.FindAll")
	@ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.FindAllResponse")
	public List<Object> findAll();

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachDirty", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.AttachDirty")
	@ResponseWrapper(localName = "attachDirtyResponse", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.AttachDirtyResponse")
	public void attachDirty(
			@WebParam(name = "arg0", targetNamespace = "") MovieChapter arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachClean", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.AttachClean")
	@ResponseWrapper(localName = "attachCleanResponse", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.AttachCleanResponse")
	public void attachClean(
			@WebParam(name = "arg0", targetNamespace = "") MovieChapter arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByModified", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.FindByModified")
	@ResponseWrapper(localName = "findByModifiedResponse", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.FindByModifiedResponse")
	public List<Object> findByModified(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCreated", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.FindByCreated")
	@ResponseWrapper(localName = "findByCreatedResponse", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.FindByCreatedResponse")
	public List<Object> findByCreated(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieFk", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.FindByMovieFk")
	@ResponseWrapper(localName = "findByMovieFkResponse", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.FindByMovieFkResponse")
	public List<Object> findByMovieFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieChapterDescription", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.FindByMovieChapterDescription")
	@ResponseWrapper(localName = "findByMovieChapterDescriptionResponse", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.FindByMovieChapterDescriptionResponse")
	public List<Object> findByMovieChapterDescription(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieChapterName", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.FindByMovieChapterName")
	@ResponseWrapper(localName = "findByMovieChapterNameResponse", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.FindByMovieChapterNameResponse")
	public List<Object> findByMovieChapterName(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieChapterStartTime", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.FindByMovieChapterStartTime")
	@ResponseWrapper(localName = "findByMovieChapterStartTimeResponse", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.FindByMovieChapterStartTimeResponse")
	public List<Object> findByMovieChapterStartTime(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieChapterEndTime", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.FindByMovieChapterEndTime")
	@ResponseWrapper(localName = "findByMovieChapterEndTimeResponse", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_chapter.FindByMovieChapterEndTimeResponse")
	public List<Object> findByMovieChapterEndTime(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

}
