package org.ski.dvx.client.hibernate.path;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * PathDAOService service = new PathDAOService();
 * PathDAODelegate portType = service.getPathDAOPort();
 * portType.save(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "PathDAOService", targetNamespace = "http://path.hibernate.server.dvx.ski.org/", wsdlLocation = "http://localhost:8080/dvx/PathDAOPort?wsdl")
public class PathDAOService extends Service {

	private final static URL PATHDAOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.ski.dvx.client.hibernate.path.PathDAOService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.ski.dvx.client.hibernate.path.PathDAOService.class
					.getResource(".");
			url = new URL(baseUrl, "http://localhost:8080/dvx/PathDAOPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/dvx/PathDAOPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		PATHDAOSERVICE_WSDL_LOCATION = url;
	}

	public PathDAOService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public PathDAOService() {
		super(PATHDAOSERVICE_WSDL_LOCATION, new QName(
				"http://path.hibernate.server.dvx.ski.org/", "PathDAOService"));
	}

	/**
	 * 
	 * @return returns PathDAODelegate
	 */
	@WebEndpoint(name = "PathDAOPort")
	public PathDAODelegate getPathDAOPort() {
		return super.getPort(new QName(
				"http://path.hibernate.server.dvx.ski.org/", "PathDAOPort"),
				PathDAODelegate.class);
	}

}
