package org.ski.dvx.client.hibernate.rating;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * RatingDAOService service = new RatingDAOService();
 * RatingDAODelegate portType = service.getRatingDAOPort();
 * portType.save(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "RatingDAOService", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", wsdlLocation = "http://localhost:8080/dvx/RatingDAOPort?wsdl")
public class RatingDAOService extends Service {

	private final static URL RATINGDAOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.ski.dvx.client.hibernate.rating.RatingDAOService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.ski.dvx.client.hibernate.rating.RatingDAOService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/dvx/RatingDAOPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/dvx/RatingDAOPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		RATINGDAOSERVICE_WSDL_LOCATION = url;
	}

	public RatingDAOService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public RatingDAOService() {
		super(RATINGDAOSERVICE_WSDL_LOCATION, new QName(
				"http://rating.hibernate.server.dvx.ski.org/",
				"RatingDAOService"));
	}

	/**
	 * 
	 * @return returns RatingDAODelegate
	 */
	@WebEndpoint(name = "RatingDAOPort")
	public RatingDAODelegate getRatingDAOPort() {
		return super.getPort(
				new QName("http://rating.hibernate.server.dvx.ski.org/",
						"RatingDAOPort"), RatingDAODelegate.class);
	}

}
