package org.ski.dvx.client.hibernate.rating;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "RatingDAODelegate", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/")
public interface RatingDAODelegate {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "save", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.SaveResponse")
	public void save(@WebParam(name = "arg0", targetNamespace = "") Rating arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "delete", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.Delete")
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.DeleteResponse")
	public void delete(
			@WebParam(name = "arg0", targetNamespace = "") Rating arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.rating.Rating
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "merge", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.Merge")
	@ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.MergeResponse")
	public Rating merge(
			@WebParam(name = "arg0", targetNamespace = "") Rating arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.rating.Rating
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findById", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindById")
	@ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindByIdResponse")
	public Rating findById(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByExample", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindByExample")
	@ResponseWrapper(localName = "findByExampleResponse", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindByExampleResponse")
	public List<Object> findByExample(
			@WebParam(name = "arg0", targetNamespace = "") Rating arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByProperty", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindByProperty")
	@ResponseWrapper(localName = "findByPropertyResponse", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindByPropertyResponse")
	public List<Object> findByProperty(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") Object arg1);

	/**
	 * 
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAll", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindAll")
	@ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindAllResponse")
	public List<Object> findAll();

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachDirty", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.AttachDirty")
	@ResponseWrapper(localName = "attachDirtyResponse", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.AttachDirtyResponse")
	public void attachDirty(
			@WebParam(name = "arg0", targetNamespace = "") Rating arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachClean", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.AttachClean")
	@ResponseWrapper(localName = "attachCleanResponse", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.AttachCleanResponse")
	public void attachClean(
			@WebParam(name = "arg0", targetNamespace = "") Rating arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByModified", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindByModified")
	@ResponseWrapper(localName = "findByModifiedResponse", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindByModifiedResponse")
	public List<Object> findByModified(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCreated", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindByCreated")
	@ResponseWrapper(localName = "findByCreatedResponse", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindByCreatedResponse")
	public List<Object> findByCreated(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByRatingUserFk", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindByRatingUserFk")
	@ResponseWrapper(localName = "findByRatingUserFkResponse", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindByRatingUserFkResponse")
	public List<Object> findByRatingUserFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByRatingLanguageFk", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindByRatingLanguageFk")
	@ResponseWrapper(localName = "findByRatingLanguageFkResponse", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindByRatingLanguageFkResponse")
	public List<Object> findByRatingLanguageFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByRatingMovieFk", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindByRatingMovieFk")
	@ResponseWrapper(localName = "findByRatingMovieFkResponse", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindByRatingMovieFkResponse")
	public List<Object> findByRatingMovieFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescriptionFk", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindByDescriptionFk")
	@ResponseWrapper(localName = "findByDescriptionFkResponse", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindByDescriptionFkResponse")
	public List<Object> findByDescriptionFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByRatingVersionFk", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindByRatingVersionFk")
	@ResponseWrapper(localName = "findByRatingVersionFkResponse", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindByRatingVersionFkResponse")
	public List<Object> findByRatingVersionFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByRatingNameShort", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindByRatingNameShort")
	@ResponseWrapper(localName = "findByRatingNameShortResponse", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindByRatingNameShortResponse")
	public List<Object> findByRatingNameShort(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByRating", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindByRating")
	@ResponseWrapper(localName = "findByRatingResponse", targetNamespace = "http://rating.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.rating.FindByRatingResponse")
	public List<Object> findByRating(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

}
