package org.ski.dvx.client.hibernate.movie;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MovieDAODelegate", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/")
public interface MovieDAODelegate {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "save", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.SaveResponse")
	public void save(@WebParam(name = "arg0", targetNamespace = "") Movie arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "delete", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.Delete")
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.DeleteResponse")
	public void delete(@WebParam(name = "arg0", targetNamespace = "") Movie arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.movie.Movie
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "merge", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.Merge")
	@ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.MergeResponse")
	public Movie merge(@WebParam(name = "arg0", targetNamespace = "") Movie arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.movie.Movie
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findById", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindById")
	@ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByIdResponse")
	public Movie findById(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByExample", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByExample")
	@ResponseWrapper(localName = "findByExampleResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByExampleResponse")
	public List<Object> findByExample(
			@WebParam(name = "arg0", targetNamespace = "") Movie arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByProperty", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByProperty")
	@ResponseWrapper(localName = "findByPropertyResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByPropertyResponse")
	public List<Object> findByProperty(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") Object arg1);

	/**
	 * 
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAll", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindAll")
	@ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindAllResponse")
	public List<Object> findAll();

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachDirty", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.AttachDirty")
	@ResponseWrapper(localName = "attachDirtyResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.AttachDirtyResponse")
	public void attachDirty(
			@WebParam(name = "arg0", targetNamespace = "") Movie arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachClean", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.AttachClean")
	@ResponseWrapper(localName = "attachCleanResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.AttachCleanResponse")
	public void attachClean(
			@WebParam(name = "arg0", targetNamespace = "") Movie arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieName", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieName")
	@ResponseWrapper(localName = "findByMovieNameResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieNameResponse")
	public List<Object> findByMovieName(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByModified", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByModified")
	@ResponseWrapper(localName = "findByModifiedResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByModifiedResponse")
	public List<Object> findByModified(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCreated", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByCreated")
	@ResponseWrapper(localName = "findByCreatedResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByCreatedResponse")
	public List<Object> findByCreated(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieSbnNumber", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieSbnNumber")
	@ResponseWrapper(localName = "findByMovieSbnNumberResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieSbnNumberResponse")
	public List<Object> findByMovieSbnNumber(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieAuthorFk", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieAuthorFk")
	@ResponseWrapper(localName = "findByMovieAuthorFkResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieAuthorFkResponse")
	public List<Object> findByMovieAuthorFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieActive", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieActive")
	@ResponseWrapper(localName = "findByMovieActiveResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieActiveResponse")
	public List<Object> findByMovieActive(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieReleased", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieReleased")
	@ResponseWrapper(localName = "findByMovieReleasedResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieReleasedResponse")
	public List<Object> findByMovieReleased(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieRatingTemp", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieRatingTemp")
	@ResponseWrapper(localName = "findByMovieRatingTempResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieRatingTempResponse")
	public List<Object> findByMovieRatingTemp(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieRatedFk", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieRatedFk")
	@ResponseWrapper(localName = "findByMovieRatedFkResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieRatedFkResponse")
	public List<Object> findByMovieRatedFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieLanguageMainFk", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieLanguageMainFk")
	@ResponseWrapper(localName = "findByMovieLanguageMainFkResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieLanguageMainFkResponse")
	public List<Object> findByMovieLanguageMainFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieRating", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieRating")
	@ResponseWrapper(localName = "findByMovieRatingResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieRatingResponse")
	public List<Object> findByMovieRating(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieQuote", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieQuote")
	@ResponseWrapper(localName = "findByMovieQuoteResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieQuoteResponse")
	public List<Object> findByMovieQuote(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieDescription", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieDescription")
	@ResponseWrapper(localName = "findByMovieDescriptionResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieDescriptionResponse")
	public List<Object> findByMovieDescription(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieExtraFeatures", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieExtraFeatures")
	@ResponseWrapper(localName = "findByMovieExtraFeaturesResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieExtraFeaturesResponse")
	public List<Object> findByMovieExtraFeatures(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieStatusFk", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieStatusFk")
	@ResponseWrapper(localName = "findByMovieStatusFkResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieStatusFkResponse")
	public List<Object> findByMovieStatusFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieRuntime", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieRuntime")
	@ResponseWrapper(localName = "findByMovieRuntimeResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieRuntimeResponse")
	public List<Object> findByMovieRuntime(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieBudget", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieBudget")
	@ResponseWrapper(localName = "findByMovieBudgetResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieBudgetResponse")
	public List<Object> findByMovieBudget(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieRevenue", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieRevenue")
	@ResponseWrapper(localName = "findByMovieRevenueResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieRevenueResponse")
	public List<Object> findByMovieRevenue(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieWebpage", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieWebpage")
	@ResponseWrapper(localName = "findByMovieWebpageResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieWebpageResponse")
	public List<Object> findByMovieWebpage(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMoviePathFk", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMoviePathFk")
	@ResponseWrapper(localName = "findByMoviePathFkResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMoviePathFkResponse")
	public List<Object> findByMoviePathFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieCountryOfOriginFk", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieCountryOfOriginFk")
	@ResponseWrapper(localName = "findByMovieCountryOfOriginFkResponse", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie.FindByMovieCountryOfOriginFkResponse")
	public List<Object> findByMovieCountryOfOriginFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

}
