package org.ski.dvx.ws.listuser;

import java.net.MalformedURLException;

import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * UserListService service = new UserListService();
 * UserListDelegate portType = service.getUserListPort();
 * portType.main(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "UserListService", targetNamespace = "http://ws.dvx.ski.org/", wsdlLocation = "http://jeff-pc:8080/dvx1/UserListPort?wsdl")
public class UserListService extends Service {

	private final static URL USERLISTSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.ski.dvx.ws.listuser.UserListService.class.getName());
	private final static String SERVER_BASE = "http://dvx.ski.org:8080/";
//	private final static String SERVER_BASE = "http://jeff-pc:8080/";

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.ski.dvx.ws.listuser.UserListService.class
					.getResource(".");
			url = new URL(baseUrl, SERVER_BASE + "dvx1/UserListPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: '" + SERVER_BASE +  "dvx1/UserListPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		USERLISTSERVICE_WSDL_LOCATION = url;
	}

	public UserListService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public UserListService() {
		super(USERLISTSERVICE_WSDL_LOCATION, new QName(
				"http://ws.dvx.ski.org/", "UserListService"));
	}

	/**
	 * 
	 * @return returns UserListDelegate
	 */
	@WebEndpoint(name = "UserListPort")
	public UserListDelegate getUserListPort() {
		return super.getPort(
				new QName("http://ws.dvx.ski.org/", "UserListPort"),
				UserListDelegate.class);
	}

}
