package org.ski.dvx.client.hibernate.movie_genre;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * MovieGenreDAOService service = new MovieGenreDAOService();
 * MovieGenreDAODelegate portType = service.getMovieGenreDAOPort();
 * portType.save(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "MovieGenreDAOService", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", wsdlLocation = "http://localhost:8080/dvx/MovieGenreDAOPort?wsdl")
public class MovieGenreDAOService extends Service {

	private final static URL MOVIEGENREDAOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.ski.dvx.client.hibernate.movie_genre.MovieGenreDAOService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.ski.dvx.client.hibernate.movie_genre.MovieGenreDAOService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/dvx/MovieGenreDAOPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/dvx/MovieGenreDAOPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		MOVIEGENREDAOSERVICE_WSDL_LOCATION = url;
	}

	public MovieGenreDAOService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public MovieGenreDAOService() {
		super(MOVIEGENREDAOSERVICE_WSDL_LOCATION, new QName(
				"http://movie_genre.hibernate.server.dvx.ski.org/",
				"MovieGenreDAOService"));
	}

	/**
	 * 
	 * @return returns MovieGenreDAODelegate
	 */
	@WebEndpoint(name = "MovieGenreDAOPort")
	public MovieGenreDAODelegate getMovieGenreDAOPort() {
		return super.getPort(new QName(
				"http://movie_genre.hibernate.server.dvx.ski.org/",
				"MovieGenreDAOPort"), MovieGenreDAODelegate.class);
	}

}
