package org.ski.dvx.client.hibernate.author;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "AuthorDAODelegate", targetNamespace = "http://author.hibernate.server.dvx.ski.org/")
public interface AuthorDAODelegate {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "save", targetNamespace = "http://author.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.author.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://author.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.author.SaveResponse")
	public void save(@WebParam(name = "arg0", targetNamespace = "") Author arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "delete", targetNamespace = "http://author.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.author.Delete")
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://author.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.author.DeleteResponse")
	public void delete(
			@WebParam(name = "arg0", targetNamespace = "") Author arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.author.Author
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "merge", targetNamespace = "http://author.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.author.Merge")
	@ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://author.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.author.MergeResponse")
	public Author merge(
			@WebParam(name = "arg0", targetNamespace = "") Author arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.author.Author
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findById", targetNamespace = "http://author.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.author.FindById")
	@ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://author.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.author.FindByIdResponse")
	public Author findById(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByExample", targetNamespace = "http://author.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.author.FindByExample")
	@ResponseWrapper(localName = "findByExampleResponse", targetNamespace = "http://author.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.author.FindByExampleResponse")
	public List<Object> findByExample(
			@WebParam(name = "arg0", targetNamespace = "") Author arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByProperty", targetNamespace = "http://author.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.author.FindByProperty")
	@ResponseWrapper(localName = "findByPropertyResponse", targetNamespace = "http://author.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.author.FindByPropertyResponse")
	public List<Object> findByProperty(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") Object arg1);

	/**
	 * 
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAll", targetNamespace = "http://author.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.author.FindAll")
	@ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://author.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.author.FindAllResponse")
	public List<Object> findAll();

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachDirty", targetNamespace = "http://author.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.author.AttachDirty")
	@ResponseWrapper(localName = "attachDirtyResponse", targetNamespace = "http://author.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.author.AttachDirtyResponse")
	public void attachDirty(
			@WebParam(name = "arg0", targetNamespace = "") Author arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachClean", targetNamespace = "http://author.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.author.AttachClean")
	@ResponseWrapper(localName = "attachCleanResponse", targetNamespace = "http://author.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.author.AttachCleanResponse")
	public void attachClean(
			@WebParam(name = "arg0", targetNamespace = "") Author arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByModified", targetNamespace = "http://author.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.author.FindByModified")
	@ResponseWrapper(localName = "findByModifiedResponse", targetNamespace = "http://author.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.author.FindByModifiedResponse")
	public List<Object> findByModified(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCreated", targetNamespace = "http://author.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.author.FindByCreated")
	@ResponseWrapper(localName = "findByCreatedResponse", targetNamespace = "http://author.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.author.FindByCreatedResponse")
	public List<Object> findByCreated(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserFk", targetNamespace = "http://author.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.author.FindByUserFk")
	@ResponseWrapper(localName = "findByUserFkResponse", targetNamespace = "http://author.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.author.FindByUserFkResponse")
	public List<Object> findByUserFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

}
