package org.ski.dvx.client.hibernate.movie_chapter;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * MovieChapterDAOService service = new MovieChapterDAOService();
 * MovieChapterDAODelegate portType = service.getMovieChapterDAOPort();
 * portType.save(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "MovieChapterDAOService", targetNamespace = "http://movie_chapter.hibernate.server.dvx.ski.org/", wsdlLocation = "http://localhost:8080/dvx/MovieChapterDAOPort?wsdl")
public class MovieChapterDAOService extends Service {

	private final static URL MOVIECHAPTERDAOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.ski.dvx.client.hibernate.movie_chapter.MovieChapterDAOService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.ski.dvx.client.hibernate.movie_chapter.MovieChapterDAOService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/dvx/MovieChapterDAOPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/dvx/MovieChapterDAOPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		MOVIECHAPTERDAOSERVICE_WSDL_LOCATION = url;
	}

	public MovieChapterDAOService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public MovieChapterDAOService() {
		super(MOVIECHAPTERDAOSERVICE_WSDL_LOCATION, new QName(
				"http://movie_chapter.hibernate.server.dvx.ski.org/",
				"MovieChapterDAOService"));
	}

	/**
	 * 
	 * @return returns MovieChapterDAODelegate
	 */
	@WebEndpoint(name = "MovieChapterDAOPort")
	public MovieChapterDAODelegate getMovieChapterDAOPort() {
		return super.getPort(new QName(
				"http://movie_chapter.hibernate.server.dvx.ski.org/",
				"MovieChapterDAOPort"), MovieChapterDAODelegate.class);
	}

}
