package org.ski.dvx.ws.moviePort;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * MovieListService service = new MovieListService();
 * MovieListDelegate portType = service.getMovieListPort();
 * portType.main(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "MovieListService", targetNamespace = "http://ws.dvx.ski.org/", wsdlLocation = "http://jeff-pc:8080/dvx1/MovieListPort?wsdl")
public class MovieListService extends Service {

	private final static URL MOVIELISTSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.ski.dvx.ws.moviePort.MovieListService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.ski.dvx.ws.moviePort.MovieListService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://jeff-pc:8080/dvx1/MovieListPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://jeff-pc:8080/dvx1/MovieListPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		MOVIELISTSERVICE_WSDL_LOCATION = url;
	}

	public MovieListService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public MovieListService() {
		super(MOVIELISTSERVICE_WSDL_LOCATION, new QName(
				"http://ws.dvx.ski.org/", "MovieListService"));
	}

	/**
	 * 
	 * @return returns MovieListDelegate
	 */
	@WebEndpoint(name = "MovieListPort")
	public MovieListDelegate getMovieListPort() {
		return super.getPort(new QName("http://ws.dvx.ski.org/",
				"MovieListPort"), MovieListDelegate.class);
	}

}
