package org.ski.dvx.client.hibernate.geocode;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "GeocodeDAODelegate", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/")
public interface GeocodeDAODelegate {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "save", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.SaveResponse")
	public void save(@WebParam(name = "arg0", targetNamespace = "") Geocode arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "delete", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.Delete")
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.DeleteResponse")
	public void delete(
			@WebParam(name = "arg0", targetNamespace = "") Geocode arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.geocode.Geocode
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "merge", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.Merge")
	@ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.MergeResponse")
	public Geocode merge(
			@WebParam(name = "arg0", targetNamespace = "") Geocode arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.geocode.Geocode
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findById", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.FindById")
	@ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.FindByIdResponse")
	public Geocode findById(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByExample", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.FindByExample")
	@ResponseWrapper(localName = "findByExampleResponse", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.FindByExampleResponse")
	public List<Object> findByExample(
			@WebParam(name = "arg0", targetNamespace = "") Geocode arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByProperty", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.FindByProperty")
	@ResponseWrapper(localName = "findByPropertyResponse", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.FindByPropertyResponse")
	public List<Object> findByProperty(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") Object arg1);

	/**
	 * 
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAll", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.FindAll")
	@ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.FindAllResponse")
	public List<Object> findAll();

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachDirty", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.AttachDirty")
	@ResponseWrapper(localName = "attachDirtyResponse", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.AttachDirtyResponse")
	public void attachDirty(
			@WebParam(name = "arg0", targetNamespace = "") Geocode arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachClean", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.AttachClean")
	@ResponseWrapper(localName = "attachCleanResponse", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.AttachCleanResponse")
	public void attachClean(
			@WebParam(name = "arg0", targetNamespace = "") Geocode arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByModified", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.FindByModified")
	@ResponseWrapper(localName = "findByModifiedResponse", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.FindByModifiedResponse")
	public List<Object> findByModified(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCreated", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.FindByCreated")
	@ResponseWrapper(localName = "findByCreatedResponse", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.FindByCreatedResponse")
	public List<Object> findByCreated(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByGeocodeLatitude", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.FindByGeocodeLatitude")
	@ResponseWrapper(localName = "findByGeocodeLatitudeResponse", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.FindByGeocodeLatitudeResponse")
	public List<Object> findByGeocodeLatitude(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByGeocodeLongitude", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.FindByGeocodeLongitude")
	@ResponseWrapper(localName = "findByGeocodeLongitudeResponse", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.FindByGeocodeLongitudeResponse")
	public List<Object> findByGeocodeLongitude(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByGeocodeRadius", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.FindByGeocodeRadius")
	@ResponseWrapper(localName = "findByGeocodeRadiusResponse", targetNamespace = "http://geocode.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.geocode.FindByGeocodeRadiusResponse")
	public List<Object> findByGeocodeRadius(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

}
