package org.ski.dvx.client.hibernate.attribute;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "AttributeDAODelegate", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/")
public interface AttributeDAODelegate {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "save", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.SaveResponse")
	public void save(
			@WebParam(name = "arg0", targetNamespace = "") Attribute arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "delete", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.Delete")
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.DeleteResponse")
	public void delete(
			@WebParam(name = "arg0", targetNamespace = "") Attribute arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.attribute.Attribute
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "merge", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.Merge")
	@ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.MergeResponse")
	public Attribute merge(
			@WebParam(name = "arg0", targetNamespace = "") Attribute arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.attribute.Attribute
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findById", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.FindById")
	@ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.FindByIdResponse")
	public Attribute findById(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByExample", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.FindByExample")
	@ResponseWrapper(localName = "findByExampleResponse", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.FindByExampleResponse")
	public List<Object> findByExample(
			@WebParam(name = "arg0", targetNamespace = "") Attribute arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByProperty", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.FindByProperty")
	@ResponseWrapper(localName = "findByPropertyResponse", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.FindByPropertyResponse")
	public List<Object> findByProperty(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") Object arg1);

	/**
	 * 
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAll", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.FindAll")
	@ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.FindAllResponse")
	public List<Object> findAll();

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachDirty", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.AttachDirty")
	@ResponseWrapper(localName = "attachDirtyResponse", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.AttachDirtyResponse")
	public void attachDirty(
			@WebParam(name = "arg0", targetNamespace = "") Attribute arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachClean", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.AttachClean")
	@ResponseWrapper(localName = "attachCleanResponse", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.AttachCleanResponse")
	public void attachClean(
			@WebParam(name = "arg0", targetNamespace = "") Attribute arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByAttibuteName", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.FindByAttibuteName")
	@ResponseWrapper(localName = "findByAttibuteNameResponse", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.FindByAttibuteNameResponse")
	public List<Object> findByAttibuteName(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByAttributeValue", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.FindByAttributeValue")
	@ResponseWrapper(localName = "findByAttributeValueResponse", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.FindByAttributeValueResponse")
	public List<Object> findByAttributeValue(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByModified", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.FindByModified")
	@ResponseWrapper(localName = "findByModifiedResponse", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.FindByModifiedResponse")
	public List<Object> findByModified(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCreated", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.FindByCreated")
	@ResponseWrapper(localName = "findByCreatedResponse", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.attribute.FindByCreatedResponse")
	public List<Object> findByCreated(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

}
