package org.ski.dvx.client.hibernate.zip_code;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ZipCodeDAOService service = new ZipCodeDAOService();
 * ZipCodeDAODelegate portType = service.getZipCodeDAOPort();
 * portType.save(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ZipCodeDAOService", targetNamespace = "http://zip_code.hibernate.server.dvx.ski.org/", wsdlLocation = "http://localhost:8080/dvx/ZipCodeDAOPort?wsdl")
public class ZipCodeDAOService extends Service {

	private final static URL ZIPCODEDAOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.ski.dvx.client.hibernate.zip_code.ZipCodeDAOService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.ski.dvx.client.hibernate.zip_code.ZipCodeDAOService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/dvx/ZipCodeDAOPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/dvx/ZipCodeDAOPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ZIPCODEDAOSERVICE_WSDL_LOCATION = url;
	}

	public ZipCodeDAOService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ZipCodeDAOService() {
		super(ZIPCODEDAOSERVICE_WSDL_LOCATION, new QName(
				"http://zip_code.hibernate.server.dvx.ski.org/",
				"ZipCodeDAOService"));
	}

	/**
	 * 
	 * @return returns ZipCodeDAODelegate
	 */
	@WebEndpoint(name = "ZipCodeDAOPort")
	public ZipCodeDAODelegate getZipCodeDAOPort() {
		return super.getPort(new QName(
				"http://zip_code.hibernate.server.dvx.ski.org/",
				"ZipCodeDAOPort"), ZipCodeDAODelegate.class);
	}

}
