/*
	Project:		DVX_App_Demo	
	File Name:		NewUser.java
	Designer:		Josh Miele
	Author:			Greg
	Contributors:	Owen Edwards					
	Created:		Oct 3, 2011	
	Copyright:	 	The Smith-Kettlewell Eye Research Institute
					© 2011 - 2011
					All Rights Reserved
					
					http://www.ski.org/
					
					The Smith-Kettlewell Eye Research Institute
					2318 Fillmore Street 
					San Francisco, CA  94115 
					415-345-2000  
				 
	Notice:			Parts of this project are based on Open Source 
					and/or Public Domain Code. Please use good judgement 
					if you include any of this project in your project.
					
	Contact:		Josh Miele
					jam@ski.org
*/

/** Class starts here **/
package org.ski.dvx.app.dialogs;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewUser.java
 *
 * Created on Oct 3, 2011, 5:39:55 PM
 */

import java.awt.Dimension;
import java.awt.Toolkit;

import org.ski.dvx.app.DVX_DB_Support;
import org.ski.dvx.app.DVX_Player;
import org.ski.dvx.hibernate.User;

/**
 *
 * @author Greg
 */
public class NewUser extends javax.swing.JFrame {

	
	DVX_Player dvx_player;	
	
	
    /** Creates new form NewUser */
    public NewUser(DVX_Player dvx_player) {
        initComponents();
        this.dvx_player = dvx_player;
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        // Determine the new location of the window
        int w = getSize().width;
        int h = getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;    

        // Move the window
        
        setLocation(x, y);
    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabelNewUser = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonAddUser = new javax.swing.JButton();
        jLabelEMailAddress = new javax.swing.JLabel();
        jLabelUserHandle = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldEMailAddress = new javax.swing.JTextField();
        jTextFieldUserHandle = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        
        jButtonCancel = new javax.swing.JButton();


        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelNewUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNewUser.setText("New User:");

        jButtonAddUser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAddUser.setText("Add New User");
        jButtonAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddUserActionPerformed(evt);
            }
        });
        
        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabelEMailAddress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelEMailAddress.setText("EMail Address:");

        jLabelUserHandle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelUserHandle.setText("User Handle:");

        jLabelPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPassword.setText("Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelUserHandle)
                    .addComponent(jLabelEMailAddress)
                    .addComponent(jLabelPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPasswordField)
                    .addComponent(jTextFieldUserHandle)
                    .addComponent(jTextFieldEMailAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(jButtonAddUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCancel)
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabelNewUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEMailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEMailAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUserHandle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUserHandle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddUser)
                    .addComponent(jButtonCancel))
                .addContainerGap())
        );


        pack();
    }// </editor-fold>
    
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {
    	// TODO add your handling code here:
    	    this.dispose();
    	}

private void jButtonAddUserActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
	
	User user = new User();
	
	user.setUserEmail(jTextFieldEMailAddress.getText());
	user.setUserPassword(jPasswordField.getText());
	user.setUserHandle(jTextFieldUserHandle.getText());
    
	user = dvx_player.getDvxDBSupport().addUser(user);
	if (user==null)
	{
		DVX_Alert alert = new DVX_Alert();
		
		alert.setMessage("User already in database. \r\n\r\nPlease use another User Handle");
		alert.setVisible(true);
		
	}
	else
	{
		DVX_Alert alert = new DVX_Alert();
		
		alert.setMessage("User \"" + jTextFieldEMailAddress.getText() + "\" - \"" + jTextFieldUserHandle.getText() + "\"\r\n\r\nsuccessfully added.");
		alert.setVisible(true);
		
		this.dispose();
	}
    
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewUser(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton jButtonAddUser;
    private javax.swing.JLabel jLabelEMailAddress;
    private javax.swing.JLabel jLabelNewUser;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUserHandle;
    private javax.swing.JTextField jPasswordField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldEMailAddress;
    private javax.swing.JTextField jTextFieldUserHandle;
    private javax.swing.JButton jButtonCancel;
   // End of variables declaration
}
