package org.ski.dvx.client.hibernate.movie_menu;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * MovieMenuDAOService service = new MovieMenuDAOService();
 * MovieMenuDAODelegate portType = service.getMovieMenuDAOPort();
 * portType.save(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "MovieMenuDAOService", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", wsdlLocation = "http://localhost:8080/dvx/MovieMenuDAOPort?wsdl")
public class MovieMenuDAOService extends Service {

	private final static URL MOVIEMENUDAOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.ski.dvx.client.hibernate.movie_menu.MovieMenuDAOService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.ski.dvx.client.hibernate.movie_menu.MovieMenuDAOService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/dvx/MovieMenuDAOPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/dvx/MovieMenuDAOPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		MOVIEMENUDAOSERVICE_WSDL_LOCATION = url;
	}

	public MovieMenuDAOService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public MovieMenuDAOService() {
		super(MOVIEMENUDAOSERVICE_WSDL_LOCATION, new QName(
				"http://movie_menu.hibernate.server.dvx.ski.org/",
				"MovieMenuDAOService"));
	}

	/**
	 * 
	 * @return returns MovieMenuDAODelegate
	 */
	@WebEndpoint(name = "MovieMenuDAOPort")
	public MovieMenuDAODelegate getMovieMenuDAOPort() {
		return super.getPort(new QName(
				"http://movie_menu.hibernate.server.dvx.ski.org/",
				"MovieMenuDAOPort"), MovieMenuDAODelegate.class);
	}

}
