package org.ski.dvx.client.hibernate.movie_menu;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MovieMenuDAODelegate", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/")
public interface MovieMenuDAODelegate {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "save", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.SaveResponse")
	public void save(
			@WebParam(name = "arg0", targetNamespace = "") MovieMenu arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "delete", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.Delete")
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.DeleteResponse")
	public void delete(
			@WebParam(name = "arg0", targetNamespace = "") MovieMenu arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.movie_menu.MovieMenu
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "merge", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.Merge")
	@ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.MergeResponse")
	public MovieMenu merge(
			@WebParam(name = "arg0", targetNamespace = "") MovieMenu arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.movie_menu.MovieMenu
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findById", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindById")
	@ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByIdResponse")
	public MovieMenu findById(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByExample", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByExample")
	@ResponseWrapper(localName = "findByExampleResponse", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByExampleResponse")
	public List<Object> findByExample(
			@WebParam(name = "arg0", targetNamespace = "") MovieMenu arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByProperty", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByProperty")
	@ResponseWrapper(localName = "findByPropertyResponse", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByPropertyResponse")
	public List<Object> findByProperty(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") Object arg1);

	/**
	 * 
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAll", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindAll")
	@ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindAllResponse")
	public List<Object> findAll();

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachDirty", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.AttachDirty")
	@ResponseWrapper(localName = "attachDirtyResponse", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.AttachDirtyResponse")
	public void attachDirty(
			@WebParam(name = "arg0", targetNamespace = "") MovieMenu arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachClean", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.AttachClean")
	@ResponseWrapper(localName = "attachCleanResponse", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.AttachCleanResponse")
	public void attachClean(
			@WebParam(name = "arg0", targetNamespace = "") MovieMenu arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByModified", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByModified")
	@ResponseWrapper(localName = "findByModifiedResponse", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByModifiedResponse")
	public List<Object> findByModified(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCreated", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByCreated")
	@ResponseWrapper(localName = "findByCreatedResponse", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByCreatedResponse")
	public List<Object> findByCreated(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByAuthorFk", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByAuthorFk")
	@ResponseWrapper(localName = "findByAuthorFkResponse", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByAuthorFkResponse")
	public List<Object> findByAuthorFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieIdFk", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByMovieIdFk")
	@ResponseWrapper(localName = "findByMovieIdFkResponse", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByMovieIdFkResponse")
	public List<Object> findByMovieIdFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByLanguageFk", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByLanguageFk")
	@ResponseWrapper(localName = "findByLanguageFkResponse", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByLanguageFkResponse")
	public List<Object> findByLanguageFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMenuActive", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByMenuActive")
	@ResponseWrapper(localName = "findByMenuActiveResponse", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByMenuActiveResponse")
	public List<Object> findByMenuActive(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMenuNumber", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByMenuNumber")
	@ResponseWrapper(localName = "findByMenuNumberResponse", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByMenuNumberResponse")
	public List<Object> findByMenuNumber(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMenuItem", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByMenuItem")
	@ResponseWrapper(localName = "findByMenuItemResponse", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByMenuItemResponse")
	public List<Object> findByMenuItem(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByDescription", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByDescription")
	@ResponseWrapper(localName = "findByDescriptionResponse", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByDescriptionResponse")
	public List<Object> findByDescription(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMenuPathFk", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByMenuPathFk")
	@ResponseWrapper(localName = "findByMenuPathFkResponse", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByMenuPathFkResponse")
	public List<Object> findByMenuPathFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMenuVersion", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByMenuVersion")
	@ResponseWrapper(localName = "findByMenuVersionResponse", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByMenuVersionResponse")
	public List<Object> findByMenuVersion(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMenuUri", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByMenuUri")
	@ResponseWrapper(localName = "findByMenuUriResponse", targetNamespace = "http://movie_menu.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_menu.FindByMenuUriResponse")
	public List<Object> findByMenuUri(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

}
