package org.ski.dvx.client.hibernate.status;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * StatusDAOService service = new StatusDAOService();
 * StatusDAODelegate portType = service.getStatusDAOPort();
 * portType.save(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "StatusDAOService", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", wsdlLocation = "http://localhost:8080/dvx/StatusDAOPort?wsdl")
public class StatusDAOService extends Service {

	private final static URL STATUSDAOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.ski.dvx.client.hibernate.status.StatusDAOService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.ski.dvx.client.hibernate.status.StatusDAOService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/dvx/StatusDAOPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/dvx/StatusDAOPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		STATUSDAOSERVICE_WSDL_LOCATION = url;
	}

	public StatusDAOService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public StatusDAOService() {
		super(STATUSDAOSERVICE_WSDL_LOCATION, new QName(
				"http://status.hibernate.server.dvx.ski.org/",
				"StatusDAOService"));
	}

	/**
	 * 
	 * @return returns StatusDAODelegate
	 */
	@WebEndpoint(name = "StatusDAOPort")
	public StatusDAODelegate getStatusDAOPort() {
		return super.getPort(
				new QName("http://status.hibernate.server.dvx.ski.org/",
						"StatusDAOPort"), StatusDAODelegate.class);
	}

}
