package org.ski.dvx.client.hibernate.status;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "StatusDAODelegate", targetNamespace = "http://status.hibernate.server.dvx.ski.org/")
public interface StatusDAODelegate {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "save", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.status.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.status.SaveResponse")
	public void save(@WebParam(name = "arg0", targetNamespace = "") Status arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "delete", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.status.Delete")
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.status.DeleteResponse")
	public void delete(
			@WebParam(name = "arg0", targetNamespace = "") Status arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.status.Status
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "merge", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.status.Merge")
	@ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.status.MergeResponse")
	public Status merge(
			@WebParam(name = "arg0", targetNamespace = "") Status arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.status.Status
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findById", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.status.FindById")
	@ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.status.FindByIdResponse")
	public Status findById(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByExample", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.status.FindByExample")
	@ResponseWrapper(localName = "findByExampleResponse", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.status.FindByExampleResponse")
	public List<Object> findByExample(
			@WebParam(name = "arg0", targetNamespace = "") Status arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByProperty", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.status.FindByProperty")
	@ResponseWrapper(localName = "findByPropertyResponse", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.status.FindByPropertyResponse")
	public List<Object> findByProperty(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") Object arg1);

	/**
	 * 
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAll", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.status.FindAll")
	@ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.status.FindAllResponse")
	public List<Object> findAll();

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachDirty", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.status.AttachDirty")
	@ResponseWrapper(localName = "attachDirtyResponse", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.status.AttachDirtyResponse")
	public void attachDirty(
			@WebParam(name = "arg0", targetNamespace = "") Status arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachClean", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.status.AttachClean")
	@ResponseWrapper(localName = "attachCleanResponse", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.status.AttachCleanResponse")
	public void attachClean(
			@WebParam(name = "arg0", targetNamespace = "") Status arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByModified", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.status.FindByModified")
	@ResponseWrapper(localName = "findByModifiedResponse", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.status.FindByModifiedResponse")
	public List<Object> findByModified(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCreated", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.status.FindByCreated")
	@ResponseWrapper(localName = "findByCreatedResponse", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.status.FindByCreatedResponse")
	public List<Object> findByCreated(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByStatusDescription", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.status.FindByStatusDescription")
	@ResponseWrapper(localName = "findByStatusDescriptionResponse", targetNamespace = "http://status.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.status.FindByStatusDescriptionResponse")
	public List<Object> findByStatusDescription(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

}
