package org.ski.dvx.client.hibernate.movie_genre;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MovieGenreDAODelegate", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/")
public interface MovieGenreDAODelegate {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "save", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.SaveResponse")
	public void save(
			@WebParam(name = "arg0", targetNamespace = "") MovieGenre arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "delete", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.Delete")
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.DeleteResponse")
	public void delete(
			@WebParam(name = "arg0", targetNamespace = "") MovieGenre arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.movie_genre.MovieGenre
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "merge", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.Merge")
	@ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.MergeResponse")
	public MovieGenre merge(
			@WebParam(name = "arg0", targetNamespace = "") MovieGenre arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.movie_genre.MovieGenre
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findById", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.FindById")
	@ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.FindByIdResponse")
	public MovieGenre findById(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByExample", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.FindByExample")
	@ResponseWrapper(localName = "findByExampleResponse", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.FindByExampleResponse")
	public List<Object> findByExample(
			@WebParam(name = "arg0", targetNamespace = "") MovieGenre arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByProperty", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.FindByProperty")
	@ResponseWrapper(localName = "findByPropertyResponse", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.FindByPropertyResponse")
	public List<Object> findByProperty(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") Object arg1);

	/**
	 * 
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAll", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.FindAll")
	@ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.FindAllResponse")
	public List<Object> findAll();

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachDirty", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.AttachDirty")
	@ResponseWrapper(localName = "attachDirtyResponse", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.AttachDirtyResponse")
	public void attachDirty(
			@WebParam(name = "arg0", targetNamespace = "") MovieGenre arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachClean", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.AttachClean")
	@ResponseWrapper(localName = "attachCleanResponse", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.AttachCleanResponse")
	public void attachClean(
			@WebParam(name = "arg0", targetNamespace = "") MovieGenre arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByModified", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.FindByModified")
	@ResponseWrapper(localName = "findByModifiedResponse", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.FindByModifiedResponse")
	public List<Object> findByModified(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCreated", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.FindByCreated")
	@ResponseWrapper(localName = "findByCreatedResponse", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.FindByCreatedResponse")
	public List<Object> findByCreated(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieGenreDescription", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.FindByMovieGenreDescription")
	@ResponseWrapper(localName = "findByMovieGenreDescriptionResponse", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.FindByMovieGenreDescriptionResponse")
	public List<Object> findByMovieGenreDescription(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieGenreDescriptionLong", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.FindByMovieGenreDescriptionLong")
	@ResponseWrapper(localName = "findByMovieGenreDescriptionLongResponse", targetNamespace = "http://movie_genre.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_genre.FindByMovieGenreDescriptionLongResponse")
	public List<Object> findByMovieGenreDescriptionLong(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

}
