package org.ski.dvx.client.hibernate.user_detail;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "UserDetailDAODelegate", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/")
public interface UserDetailDAODelegate {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "save", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.SaveResponse")
	public void save(
			@WebParam(name = "arg0", targetNamespace = "") UserDetail arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "delete", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.Delete")
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.DeleteResponse")
	public void delete(
			@WebParam(name = "arg0", targetNamespace = "") UserDetail arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.user_detail.UserDetail
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "merge", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.Merge")
	@ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.MergeResponse")
	public UserDetail merge(
			@WebParam(name = "arg0", targetNamespace = "") UserDetail arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.user_detail.UserDetail
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findById", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindById")
	@ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByIdResponse")
	public UserDetail findById(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByExample", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByExample")
	@ResponseWrapper(localName = "findByExampleResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByExampleResponse")
	public List<Object> findByExample(
			@WebParam(name = "arg0", targetNamespace = "") UserDetail arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByProperty", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByProperty")
	@ResponseWrapper(localName = "findByPropertyResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByPropertyResponse")
	public List<Object> findByProperty(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") Object arg1);

	/**
	 * 
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAll", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindAll")
	@ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindAllResponse")
	public List<Object> findAll();

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachDirty", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.AttachDirty")
	@ResponseWrapper(localName = "attachDirtyResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.AttachDirtyResponse")
	public void attachDirty(
			@WebParam(name = "arg0", targetNamespace = "") UserDetail arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachClean", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.AttachClean")
	@ResponseWrapper(localName = "attachCleanResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.AttachCleanResponse")
	public void attachClean(
			@WebParam(name = "arg0", targetNamespace = "") UserDetail arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByModified", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByModified")
	@ResponseWrapper(localName = "findByModifiedResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByModifiedResponse")
	public List<Object> findByModified(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCreated", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByCreated")
	@ResponseWrapper(localName = "findByCreatedResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByCreatedResponse")
	public List<Object> findByCreated(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserDetailUserFk", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailUserFk")
	@ResponseWrapper(localName = "findByUserDetailUserFkResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailUserFkResponse")
	public List<Object> findByUserDetailUserFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserDetailFirstName", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailFirstName")
	@ResponseWrapper(localName = "findByUserDetailFirstNameResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailFirstNameResponse")
	public List<Object> findByUserDetailFirstName(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserDetailLastName", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailLastName")
	@ResponseWrapper(localName = "findByUserDetailLastNameResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailLastNameResponse")
	public List<Object> findByUserDetailLastName(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserDetailEmail", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailEmail")
	@ResponseWrapper(localName = "findByUserDetailEmailResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailEmailResponse")
	public List<Object> findByUserDetailEmail(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserDetailAddress1", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailAddress1")
	@ResponseWrapper(localName = "findByUserDetailAddress1Response", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailAddress1Response")
	public List<Object> findByUserDetailAddress1(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserDetailAddress2", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailAddress2")
	@ResponseWrapper(localName = "findByUserDetailAddress2Response", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailAddress2Response")
	public List<Object> findByUserDetailAddress2(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserDetailCityFk", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailCityFk")
	@ResponseWrapper(localName = "findByUserDetailCityFkResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailCityFkResponse")
	public List<Object> findByUserDetailCityFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserDetailStateFk", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailStateFk")
	@ResponseWrapper(localName = "findByUserDetailStateFkResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailStateFkResponse")
	public List<Object> findByUserDetailStateFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserDetailZipCodeFk", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailZipCodeFk")
	@ResponseWrapper(localName = "findByUserDetailZipCodeFkResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailZipCodeFkResponse")
	public List<Object> findByUserDetailZipCodeFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserDetailCountryFk", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailCountryFk")
	@ResponseWrapper(localName = "findByUserDetailCountryFkResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailCountryFkResponse")
	public List<Object> findByUserDetailCountryFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserDetailWorkPhoneNumber", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailWorkPhoneNumber")
	@ResponseWrapper(localName = "findByUserDetailWorkPhoneNumberResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailWorkPhoneNumberResponse")
	public List<Object> findByUserDetailWorkPhoneNumber(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserDetailHomePhoneNumber", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailHomePhoneNumber")
	@ResponseWrapper(localName = "findByUserDetailHomePhoneNumberResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailHomePhoneNumberResponse")
	public List<Object> findByUserDetailHomePhoneNumber(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserDetailCellPhoneNumber", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailCellPhoneNumber")
	@ResponseWrapper(localName = "findByUserDetailCellPhoneNumberResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailCellPhoneNumberResponse")
	public List<Object> findByUserDetailCellPhoneNumber(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserDetailSubscriptionStart", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailSubscriptionStart")
	@ResponseWrapper(localName = "findByUserDetailSubscriptionStartResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailSubscriptionStartResponse")
	public List<Object> findByUserDetailSubscriptionStart(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserDetailSubscriptionEndDate", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailSubscriptionEndDate")
	@ResponseWrapper(localName = "findByUserDetailSubscriptionEndDateResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailSubscriptionEndDateResponse")
	public List<Object> findByUserDetailSubscriptionEndDate(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserDetailActive", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailActive")
	@ResponseWrapper(localName = "findByUserDetailActiveResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailActiveResponse")
	public List<Object> findByUserDetailActive(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserDetailYearOfBirth", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailYearOfBirth")
	@ResponseWrapper(localName = "findByUserDetailYearOfBirthResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailYearOfBirthResponse")
	public List<Object> findByUserDetailYearOfBirth(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserDetailGender", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailGender")
	@ResponseWrapper(localName = "findByUserDetailGenderResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailGenderResponse")
	public List<Object> findByUserDetailGender(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserDetailVisionAbility", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailVisionAbility")
	@ResponseWrapper(localName = "findByUserDetailVisionAbilityResponse", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.user_detail.FindByUserDetailVisionAbilityResponse")
	public List<Object> findByUserDetailVisionAbility(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

}
