package org.ski.dvx.client.hibernate.user_detail;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * UserDetailDAOService service = new UserDetailDAOService();
 * UserDetailDAODelegate portType = service.getUserDetailDAOPort();
 * portType.save(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "UserDetailDAOService", targetNamespace = "http://user_detail.hibernate.server.dvx.ski.org/", wsdlLocation = "http://localhost:8080/dvx/UserDetailDAOPort?wsdl")
public class UserDetailDAOService extends Service {

	private final static URL USERDETAILDAOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.ski.dvx.client.hibernate.user_detail.UserDetailDAOService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.ski.dvx.client.hibernate.user_detail.UserDetailDAOService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/dvx/UserDetailDAOPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/dvx/UserDetailDAOPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		USERDETAILDAOSERVICE_WSDL_LOCATION = url;
	}

	public UserDetailDAOService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public UserDetailDAOService() {
		super(USERDETAILDAOSERVICE_WSDL_LOCATION, new QName(
				"http://user_detail.hibernate.server.dvx.ski.org/",
				"UserDetailDAOService"));
	}

	/**
	 * 
	 * @return returns UserDetailDAODelegate
	 */
	@WebEndpoint(name = "UserDetailDAOPort")
	public UserDetailDAODelegate getUserDetailDAOPort() {
		return super.getPort(new QName(
				"http://user_detail.hibernate.server.dvx.ski.org/",
				"UserDetailDAOPort"), UserDetailDAODelegate.class);
	}

}
