package org.ski.dvx.client.hibernate.state;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "StateDAODelegate", targetNamespace = "http://state.hibernate.server.dvx.ski.org/")
public interface StateDAODelegate {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "save", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.SaveResponse")
	public void save(@WebParam(name = "arg0", targetNamespace = "") State arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "delete", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.Delete")
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.DeleteResponse")
	public void delete(@WebParam(name = "arg0", targetNamespace = "") State arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.state.State
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "merge", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.Merge")
	@ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.MergeResponse")
	public State merge(@WebParam(name = "arg0", targetNamespace = "") State arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.state.State
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findById", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.FindById")
	@ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.FindByIdResponse")
	public State findById(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByExample", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.FindByExample")
	@ResponseWrapper(localName = "findByExampleResponse", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.FindByExampleResponse")
	public List<Object> findByExample(
			@WebParam(name = "arg0", targetNamespace = "") State arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByProperty", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.FindByProperty")
	@ResponseWrapper(localName = "findByPropertyResponse", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.FindByPropertyResponse")
	public List<Object> findByProperty(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") Object arg1);

	/**
	 * 
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAll", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.FindAll")
	@ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.FindAllResponse")
	public List<Object> findAll();

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachDirty", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.AttachDirty")
	@ResponseWrapper(localName = "attachDirtyResponse", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.AttachDirtyResponse")
	public void attachDirty(
			@WebParam(name = "arg0", targetNamespace = "") State arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachClean", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.AttachClean")
	@ResponseWrapper(localName = "attachCleanResponse", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.AttachCleanResponse")
	public void attachClean(
			@WebParam(name = "arg0", targetNamespace = "") State arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByModified", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.FindByModified")
	@ResponseWrapper(localName = "findByModifiedResponse", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.FindByModifiedResponse")
	public List<Object> findByModified(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCreated", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.FindByCreated")
	@ResponseWrapper(localName = "findByCreatedResponse", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.FindByCreatedResponse")
	public List<Object> findByCreated(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByStateName", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.FindByStateName")
	@ResponseWrapper(localName = "findByStateNameResponse", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.FindByStateNameResponse")
	public List<Object> findByStateName(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByStateNameShort", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.FindByStateNameShort")
	@ResponseWrapper(localName = "findByStateNameShortResponse", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.FindByStateNameShortResponse")
	public List<Object> findByStateNameShort(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByStateCountryFk", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.FindByStateCountryFk")
	@ResponseWrapper(localName = "findByStateCountryFkResponse", targetNamespace = "http://state.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.state.FindByStateCountryFkResponse")
	public List<Object> findByStateCountryFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

}
