package org.ski.dvx.client.hibernate.movie_cast;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MovieCastDAODelegate", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/")
public interface MovieCastDAODelegate {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "save", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.SaveResponse")
	public void save(
			@WebParam(name = "arg0", targetNamespace = "") MovieCast arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "delete", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.Delete")
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.DeleteResponse")
	public void delete(
			@WebParam(name = "arg0", targetNamespace = "") MovieCast arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.movie_cast.MovieCast
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "merge", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.Merge")
	@ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.MergeResponse")
	public MovieCast merge(
			@WebParam(name = "arg0", targetNamespace = "") MovieCast arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.movie_cast.MovieCast
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findById", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.FindById")
	@ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.FindByIdResponse")
	public MovieCast findById(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByExample", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.FindByExample")
	@ResponseWrapper(localName = "findByExampleResponse", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.FindByExampleResponse")
	public List<Object> findByExample(
			@WebParam(name = "arg0", targetNamespace = "") MovieCast arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByProperty", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.FindByProperty")
	@ResponseWrapper(localName = "findByPropertyResponse", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.FindByPropertyResponse")
	public List<Object> findByProperty(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") Object arg1);

	/**
	 * 
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAll", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.FindAll")
	@ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.FindAllResponse")
	public List<Object> findAll();

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachDirty", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.AttachDirty")
	@ResponseWrapper(localName = "attachDirtyResponse", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.AttachDirtyResponse")
	public void attachDirty(
			@WebParam(name = "arg0", targetNamespace = "") MovieCast arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachClean", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.AttachClean")
	@ResponseWrapper(localName = "attachCleanResponse", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.AttachCleanResponse")
	public void attachClean(
			@WebParam(name = "arg0", targetNamespace = "") MovieCast arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByModified", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.FindByModified")
	@ResponseWrapper(localName = "findByModifiedResponse", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.FindByModifiedResponse")
	public List<Object> findByModified(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCreated", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.FindByCreated")
	@ResponseWrapper(localName = "findByCreatedResponse", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.FindByCreatedResponse")
	public List<Object> findByCreated(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieCastMovieIdFk", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.FindByMovieCastMovieIdFk")
	@ResponseWrapper(localName = "findByMovieCastMovieIdFkResponse", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.FindByMovieCastMovieIdFkResponse")
	public List<Object> findByMovieCastMovieIdFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieCastCrewCastIdFk", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.FindByMovieCastCrewCastIdFk")
	@ResponseWrapper(localName = "findByMovieCastCrewCastIdFkResponse", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.FindByMovieCastCrewCastIdFkResponse")
	public List<Object> findByMovieCastCrewCastIdFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieCastRoleOrder", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.FindByMovieCastRoleOrder")
	@ResponseWrapper(localName = "findByMovieCastRoleOrderResponse", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.FindByMovieCastRoleOrderResponse")
	public List<Object> findByMovieCastRoleOrder(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieCastRoleName", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.FindByMovieCastRoleName")
	@ResponseWrapper(localName = "findByMovieCastRoleNameResponse", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.FindByMovieCastRoleNameResponse")
	public List<Object> findByMovieCastRoleName(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieCastRoleDescription", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.FindByMovieCastRoleDescription")
	@ResponseWrapper(localName = "findByMovieCastRoleDescriptionResponse", targetNamespace = "http://movie_cast.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.movie_cast.FindByMovieCastRoleDescriptionResponse")
	public List<Object> findByMovieCastRoleDescription(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

}
