package org.ski.dvx.client.hibernate.movie;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * MovieDAOService service = new MovieDAOService();
 * MovieDAODelegate portType = service.getMovieDAOPort();
 * portType.save(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "MovieDAOService", targetNamespace = "http://movie.hibernate.server.dvx.ski.org/", wsdlLocation = "http://localhost:8080/dvx/MovieDAOPort?wsdl")
public class MovieDAOService extends Service {

	private final static URL MOVIEDAOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.ski.dvx.client.hibernate.movie.MovieDAOService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.ski.dvx.client.hibernate.movie.MovieDAOService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/dvx/MovieDAOPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/dvx/MovieDAOPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		MOVIEDAOSERVICE_WSDL_LOCATION = url;
	}

	public MovieDAOService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public MovieDAOService() {
		super(MOVIEDAOSERVICE_WSDL_LOCATION,
				new QName("http://movie.hibernate.server.dvx.ski.org/",
						"MovieDAOService"));
	}

	/**
	 * 
	 * @return returns MovieDAODelegate
	 */
	@WebEndpoint(name = "MovieDAOPort")
	public MovieDAODelegate getMovieDAOPort() {
		return super.getPort(new QName(
				"http://movie.hibernate.server.dvx.ski.org/", "MovieDAOPort"),
				MovieDAODelegate.class);
	}

}
