package org.ski.dvx.client.hibernate.attribute;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * AttributeDAOService service = new AttributeDAOService();
 * AttributeDAODelegate portType = service.getAttributeDAOPort();
 * portType.save(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "AttributeDAOService", targetNamespace = "http://attribute.hibernate.server.dvx.ski.org/", wsdlLocation = "http://localhost:8080/dvx/AttributeDAOPort?wsdl")
public class AttributeDAOService extends Service {

	private final static URL ATTRIBUTEDAOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.ski.dvx.client.hibernate.attribute.AttributeDAOService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.ski.dvx.client.hibernate.attribute.AttributeDAOService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/dvx/AttributeDAOPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/dvx/AttributeDAOPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ATTRIBUTEDAOSERVICE_WSDL_LOCATION = url;
	}

	public AttributeDAOService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public AttributeDAOService() {
		super(ATTRIBUTEDAOSERVICE_WSDL_LOCATION, new QName(
				"http://attribute.hibernate.server.dvx.ski.org/",
				"AttributeDAOService"));
	}

	/**
	 * 
	 * @return returns AttributeDAODelegate
	 */
	@WebEndpoint(name = "AttributeDAOPort")
	public AttributeDAODelegate getAttributeDAOPort() {
		return super.getPort(new QName(
				"http://attribute.hibernate.server.dvx.ski.org/",
				"AttributeDAOPort"), AttributeDAODelegate.class);
	}

}
