package org.ski.dvx.client.hibernate.transaction_log;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "TransactionLogDAODelegate", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/")
public interface TransactionLogDAODelegate {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "save", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.SaveResponse")
	public void save(
			@WebParam(name = "arg0", targetNamespace = "") TransactionLog arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "delete", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.Delete")
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.DeleteResponse")
	public void delete(
			@WebParam(name = "arg0", targetNamespace = "") TransactionLog arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns
	 *         org.ski.dvx.client.hibernate.transaction_log.TransactionLog
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "merge", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.Merge")
	@ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.MergeResponse")
	public TransactionLog merge(
			@WebParam(name = "arg0", targetNamespace = "") TransactionLog arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns
	 *         org.ski.dvx.client.hibernate.transaction_log.TransactionLog
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findById", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.FindById")
	@ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.FindByIdResponse")
	public TransactionLog findById(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByExample", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.FindByExample")
	@ResponseWrapper(localName = "findByExampleResponse", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.FindByExampleResponse")
	public List<Object> findByExample(
			@WebParam(name = "arg0", targetNamespace = "") TransactionLog arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByProperty", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.FindByProperty")
	@ResponseWrapper(localName = "findByPropertyResponse", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.FindByPropertyResponse")
	public List<Object> findByProperty(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") Object arg1);

	/**
	 * 
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAll", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.FindAll")
	@ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.FindAllResponse")
	public List<Object> findAll();

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachDirty", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.AttachDirty")
	@ResponseWrapper(localName = "attachDirtyResponse", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.AttachDirtyResponse")
	public void attachDirty(
			@WebParam(name = "arg0", targetNamespace = "") TransactionLog arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachClean", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.AttachClean")
	@ResponseWrapper(localName = "attachCleanResponse", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.AttachCleanResponse")
	public void attachClean(
			@WebParam(name = "arg0", targetNamespace = "") TransactionLog arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByModified", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.FindByModified")
	@ResponseWrapper(localName = "findByModifiedResponse", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.FindByModifiedResponse")
	public List<Object> findByModified(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCreated", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.FindByCreated")
	@ResponseWrapper(localName = "findByCreatedResponse", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.FindByCreatedResponse")
	public List<Object> findByCreated(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByUserFk", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.FindByUserFk")
	@ResponseWrapper(localName = "findByUserFkResponse", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.FindByUserFkResponse")
	public List<Object> findByUserFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByMovieFk", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.FindByMovieFk")
	@ResponseWrapper(localName = "findByMovieFkResponse", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.FindByMovieFkResponse")
	public List<Object> findByMovieFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByTransactionType", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.FindByTransactionType")
	@ResponseWrapper(localName = "findByTransactionTypeResponse", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.FindByTransactionTypeResponse")
	public List<Object> findByTransactionType(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByTransactionLevel", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.FindByTransactionLevel")
	@ResponseWrapper(localName = "findByTransactionLevelResponse", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.FindByTransactionLevelResponse")
	public List<Object> findByTransactionLevel(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByTransactionDetails", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.FindByTransactionDetails")
	@ResponseWrapper(localName = "findByTransactionDetailsResponse", targetNamespace = "http://transaction_log.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.transaction_log.FindByTransactionDetailsResponse")
	public List<Object> findByTransactionDetails(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

}
