package org.ski.dvx.client.hibernate.poster;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "PosterDAODelegate", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/")
public interface PosterDAODelegate {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "save", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.SaveResponse")
	public void save(@WebParam(name = "arg0", targetNamespace = "") Poster arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "delete", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.Delete")
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.DeleteResponse")
	public void delete(
			@WebParam(name = "arg0", targetNamespace = "") Poster arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.poster.Poster
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "merge", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.Merge")
	@ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.MergeResponse")
	public Poster merge(
			@WebParam(name = "arg0", targetNamespace = "") Poster arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.poster.Poster
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findById", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.FindById")
	@ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.FindByIdResponse")
	public Poster findById(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByExample", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.FindByExample")
	@ResponseWrapper(localName = "findByExampleResponse", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.FindByExampleResponse")
	public List<Object> findByExample(
			@WebParam(name = "arg0", targetNamespace = "") Poster arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByProperty", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.FindByProperty")
	@ResponseWrapper(localName = "findByPropertyResponse", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.FindByPropertyResponse")
	public List<Object> findByProperty(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") Object arg1);

	/**
	 * 
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAll", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.FindAll")
	@ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.FindAllResponse")
	public List<Object> findAll();

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachDirty", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.AttachDirty")
	@ResponseWrapper(localName = "attachDirtyResponse", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.AttachDirtyResponse")
	public void attachDirty(
			@WebParam(name = "arg0", targetNamespace = "") Poster arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachClean", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.AttachClean")
	@ResponseWrapper(localName = "attachCleanResponse", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.AttachCleanResponse")
	public void attachClean(
			@WebParam(name = "arg0", targetNamespace = "") Poster arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByModified", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.FindByModified")
	@ResponseWrapper(localName = "findByModifiedResponse", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.FindByModifiedResponse")
	public List<Object> findByModified(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCreated", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.FindByCreated")
	@ResponseWrapper(localName = "findByCreatedResponse", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.FindByCreatedResponse")
	public List<Object> findByCreated(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByPosterMovieIdFk", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.FindByPosterMovieIdFk")
	@ResponseWrapper(localName = "findByPosterMovieIdFkResponse", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.FindByPosterMovieIdFkResponse")
	public List<Object> findByPosterMovieIdFk(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByPosterName", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.FindByPosterName")
	@ResponseWrapper(localName = "findByPosterNameResponse", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.FindByPosterNameResponse")
	public List<Object> findByPosterName(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByPosterUrl", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.FindByPosterUrl")
	@ResponseWrapper(localName = "findByPosterUrlResponse", targetNamespace = "http://poster.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.poster.FindByPosterUrlResponse")
	public List<Object> findByPosterUrl(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

}
