package org.ski.dvx.client.hibernate.continent;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ContinentDAODelegate", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/")
public interface ContinentDAODelegate {

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "save", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.continent.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.continent.SaveResponse")
	public void save(
			@WebParam(name = "arg0", targetNamespace = "") Continent arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "delete", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.continent.Delete")
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.continent.DeleteResponse")
	public void delete(
			@WebParam(name = "arg0", targetNamespace = "") Continent arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.continent.Continent
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "merge", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.continent.Merge")
	@ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.continent.MergeResponse")
	public Continent merge(
			@WebParam(name = "arg0", targetNamespace = "") Continent arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns org.ski.dvx.client.hibernate.continent.Continent
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findById", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.continent.FindById")
	@ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.continent.FindByIdResponse")
	public Continent findById(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByExample", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.continent.FindByExample")
	@ResponseWrapper(localName = "findByExampleResponse", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.continent.FindByExampleResponse")
	public List<Object> findByExample(
			@WebParam(name = "arg0", targetNamespace = "") Continent arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByProperty", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.continent.FindByProperty")
	@ResponseWrapper(localName = "findByPropertyResponse", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.continent.FindByPropertyResponse")
	public List<Object> findByProperty(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") Object arg1);

	/**
	 * 
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAll", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.continent.FindAll")
	@ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.continent.FindAllResponse")
	public List<Object> findAll();

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachDirty", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.continent.AttachDirty")
	@ResponseWrapper(localName = "attachDirtyResponse", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.continent.AttachDirtyResponse")
	public void attachDirty(
			@WebParam(name = "arg0", targetNamespace = "") Continent arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "attachClean", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.continent.AttachClean")
	@ResponseWrapper(localName = "attachCleanResponse", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.continent.AttachCleanResponse")
	public void attachClean(
			@WebParam(name = "arg0", targetNamespace = "") Continent arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByModified", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.continent.FindByModified")
	@ResponseWrapper(localName = "findByModifiedResponse", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.continent.FindByModifiedResponse")
	public List<Object> findByModified(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByCreated", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.continent.FindByCreated")
	@ResponseWrapper(localName = "findByCreatedResponse", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.continent.FindByCreatedResponse")
	public List<Object> findByCreated(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.Object>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findByContinentName", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.continent.FindByContinentName")
	@ResponseWrapper(localName = "findByContinentNameResponse", targetNamespace = "http://continent.hibernate.server.dvx.ski.org/", className = "org.ski.dvx.client.hibernate.continent.FindByContinentNameResponse")
	public List<Object> findByContinentName(
			@WebParam(name = "arg0", targetNamespace = "") Object arg0);

}
